"use client";
import { useEffect, useState } from "react";
import type { summarizeUsage } from "../../lib/usage";
import { passages } from "../../content/passages";
import "./usage.css";
type Dashboard={learners:string[];learner:string|null;asOf:number;usage:ReturnType<typeof summarizeUsage>;learning:{skills:{skill:string;correct:number;total:number}[];trends:{level:string;count:number;recent:number|null;earlier:number|null}[];checkpoints:{date:number;level:string;score:number;condition:string}[];phraseReviews:number}};
const date=(value:number|null)=>value?new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(value):"Not recorded yet";
const duration=(ms:number)=>ms<60000?`${Math.floor(ms/1000)} sec`:`${Math.floor(ms/60000)} min ${Math.floor(ms/1000)%60} sec`;
function sourceTitle(source:string){return source.startsWith("library:")?passages.find(p=>"library:"+p.id===source)?.title||"Library passage":"Studio · "+source.split(":").slice(1).join(" · ")}
export default function UsageDashboard(){
  const [days,setDays]=useState(30),[learner,setLearner]=useState(""),[revision,setRevision]=useState(0),[data,setData]=useState<Dashboard|null>(null),[error,setError]=useState(""),[status,setStatus]=useState(0);
  useEffect(()=>{const controller=new AbortController();setData(null);setError("");setStatus(0);
    fetch(`/api/owner-usage?days=${days}${learner?"&learner="+encodeURIComponent(learner):""}`,{cache:"no-store",signal:controller.signal}).then(async r=>{const body=await r.json();if(controller.signal.aborted)return;setStatus(r.status);if(!r.ok){setError(body.error||"Could not load usage.");return}setData(body)}).catch(()=>{if(!controller.signal.aborted)setError("Could not reach the dashboard. Check your connection and retry.")});return()=>controller.abort();
  },[days,learner,revision]);
  return <main className="usage-page"><nav aria-label="Owner navigation"><a href="/">← À l’Oreille</a><a href="/feedback">Feedback inbox →</a></nav><header><p className="usage-eyebrow">Private · owner only</p><h1>A window into practice.</h1><p>Understand Nikki’s rhythm. Find places to improve the learning experience.</p></header>
    <div className="usage-controls"><label>Show <select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select></label>{data&&data.learners.length>1&&<label>Learner <select value={data.learner||""} onChange={e=>setLearner(e.target.value)}>{data.learners.map(email=><option key={email}>{email}</option>)}</select></label>}<button onClick={()=>setRevision(r=>r+1)}>Refresh</button></div>
    {error?<section role="alert" className="usage-notice"><h2>{status===403?"Owner account required":status===401?"Sign in to continue":"Unable to load usage"}</h2><p>{error}</p>{[401,403].includes(status)&&<a href="/signin-with-chatgpt?return_to=%2Fusage">Sign in with the owner account →</a>}</section>:!data?<p role="status">Loading private usage…</p>:<>
    <p className="usage-caption">{data.learner||"No invited learner configured"} · Updated {date(data.asOf)} · All dates Eastern time</p>
    {!data.usage.trackingSince&&<p className="usage-notice">No activity measured yet. This dashboard begins collecting usage after the updated app is published and opened. Earlier sessions have no reliable time or stopping-point history.</p>}
    <section aria-labelledby="usage-title"><h2 id="usage-title">Usage <small>Participation, not proficiency</small></h2><div className="usage-metrics"><article><span>Last active · all time</span><strong className="usage-date">{date(data.usage.lastActive)}</strong><p>Last measured foreground activity.</p></article><article><span>Practice days this week</span><strong>{data.usage.practiceDaysThisWeek}<small> / 7</small></strong><p>Monday–Sunday. Library or Studio activity.</p></article><article><span>Active practice · last {days} days</span><strong>{duration(data.usage.activeMs)}</strong><p>Visible, focused practice; overlapping time counted once.</p></article></div>
    <div className="usage-table-wrap"><table><caption>Library and Studio · last {days} days</caption><thead><tr><th scope="col">Practice area</th><th scope="col">Sessions completed</th><th scope="col">Active practice time</th></tr></thead><tbody>{data.usage.sources.map(row=><tr key={row.name}><th scope="row">{row.name}</th><td>{row.completed}</td><td>{duration(row.activeMs)}</td></tr>)}</tbody></table></div><p className="usage-caption">A completed session has all four steps confirmed by the app—even when no new XP is awarded. Opening a tab is not a completed session. Overlapping areas may not add up to the deduplicated total.</p></section>
    <section aria-labelledby="stops-title"><h2 id="stops-title">Where sessions pause</h2><p>Last step reached in unfinished sessions with no activity for at least five minutes. This is a clue to investigate, not proof of difficulty or frustration.</p><ol className="usage-stages">{data.usage.stops.map((step,i)=><li key={step.name}><span className="usage-step-number">{i+1}</span><h3>{step.name}</h3><strong>{step.library+step.studio}</strong><p>{step.library} Library · {step.studio} Studio</p></li>)}</ol>
    <details><summary>Session history ({Math.min(data.usage.recentTotal,50)} of {data.usage.recentTotal})</summary><div className="usage-table-wrap"><table><thead><tr><th>Last active</th><th>Content</th><th>Last step</th><th>Status</th><th>Active time</th></tr></thead><tbody>{data.usage.recent.map(row=><tr key={row.id}><td>{date(row.lastActiveAt)}</td><td>{sourceTitle(row.source)}</td><td>{["First listen","Decode","Shadow","Retell"][row.stage]}</td><td>{row.status}</td><td>{duration(row.activeMs)}</td></tr>)}</tbody></table></div>{!data.usage.recent.length&&<p>No measured practice sessions in this period.</p>}</details></section>
    <section className="usage-learning" aria-labelledby="learning-title"><p className="usage-eyebrow">Separate evidence</p><h2 id="learning-title">What is changing in her French?</h2><p>XP and minutes measure participation, not ability. These signals stay separate; none certifies a CEFR level.</p><h3>Listening checkpoints</h3>{!data.learning.checkpoints.length?<p>No fixed-answer checkpoints in this period. A first checkpoint gives a starting point; later checks offer more evidence.</p>:<div className="usage-table-wrap"><table><thead><tr><th>Date</th><th>Material level</th><th>Result</th><th>Listening condition</th></tr></thead><tbody>{data.learning.checkpoints.map((check,i)=><tr key={i}><td>{date(check.date)}</td><td>{check.level}</td><td>{check.score}%</td><td>{check.condition==="first"?"First listen":"With replays"}</td></tr>)}</tbody></table></div>}<p className="usage-caption">Fixed answer keys. Different forms and replay conditions are not directly interchangeable.</p>
    {data.learning.skills.length>0&&<ul>{data.learning.skills.map(s=><li key={s.skill}>{s.skill}: {s.correct} / {s.total} correct checkpoint questions (mixed listening conditions).</li>)}</ul>}
    <h3>First-listen Library observations</h3>{!data.learning.trends.length?<p>No eligible first-listen observations yet.</p>:data.learning.trends.map(t=><p key={t.level}><strong>{t.level}</strong> · {t.count} observations · {t.recent===null?"Need four observations for a comparison.":`Recent two average ${t.recent}% · previous two ${t.earlier}%`}</p>)}<p className="usage-caption">AI coaching estimates, grouped by material level. Excludes familiar passages, replays, and uncalibrated Studio clips; content difficulty can still differ.</p><p>{data.learning.phraseReviews} saved-phrase reviews in this period. Ratings are self-reported, not tested mastery.</p></section>
    <details className="usage-method"><summary>How these numbers are measured</summary><p>Measured history begins {date(data.usage.trackingSince)}. Time is estimated in short intervals while the app is visible and focused. After 60 seconds without interaction, time stops unless audio or video is playing. Hidden tabs, long timer gaps and overlapping intervals are excluded. Recordings and typed content are not collected by usage tracking.</p><p>Only Library and Studio loops count toward practice time and practice days. Browsing, phrase review and checkpoints outside those loops can update “last active,” but are excluded from loop time. A new practice session begins on entering a passage, changing a Studio selection, or returning after 30 minutes of inactivity.</p><p>Network loss, closing the browser, clock differences, or blocked requests may leave gaps. Studio timeline adjustments and leaving a lesson can create unfinished sessions. Session totals cover the selected rolling period; practice days always cover the current week. Refresh to update—this is not a live presence indicator.</p></details>
    </>}
  </main>;
}
