type Question={skill:string;prompt:string;options:string[];answer:number};
export type Announcement={id:string;title:string;level:string;text:string;questions:Question[];language?:"fr"|"sv";category?:"situations"};
const q=(skill:string,prompt:string,options:string[],answer:number):Question=>({skill,prompt,options,answer});
export const announcements:Announcement[]=[
 {id:"sv-butik",language:"sv",title:"The shop is closing",level:"A1",text:"Butiken stänger om fem minuter. Gå till kassan, tack. Utgången är till höger.",questions:[q("Details","When does the shop close?",["In five minutes","In fifteen minutes","At five"],0),q("Action","Where should you go?",["Home immediately","To the checkout","To the café"],1),q("Details","Where is the exit?",["Upstairs","Left","Right"],2)]},
 {id:"sv-tag",language:"sv",title:"A train platform",level:"A1",text:"Tåget till Uppsala går från spår tre. Det går klockan tio. Ha biljetten redo, tack.",questions:[q("Details","Which platform?",["Two","Three","Ten"],1),q("Details","When does it leave?",["At ten","At three","At twelve"],0),q("Action","What should be ready?",["Your bag","Cash","Your ticket"],2)]},
 {id:"sv-bestallning",language:"sv",title:"Your coffee is ready",level:"A1",text:"Nummer tolv! Ditt kaffe är klart. Hämta det här vid kassan. Mjölk och socker finns på bordet.",questions:[q("Details","Which number is called?",["Twenty","Two","Twelve"],2),q("Action","Where do you collect the coffee?",["At the checkout","At your table","Outside"],0),q("Details","What is on the table?",["Bread and butter","Milk and sugar","Coffee and tea"],1)]},
 {id:"mall-closing",title:"The mall closes soon",level:"B1",text:"Votre attention, s’il vous plaît. Le centre commercial fermera ses portes dans cinq minutes. Merci de terminer vos achats et de vous diriger vers les caisses. La sortie du parking reste ouverte pendant trente minutes après la fermeture des magasins.",questions:[q("Details","When do the shops close?",["In thirty minutes","In five minutes","In fifteen minutes"],1),q("Action","What should shoppers do now?",["Go to the checkouts","Wait in the parking lot","Return tomorrow"],0),q("Details","What stays open longer?",["The cafés","The shops","The parking exit"],2)]},
 {id:"mall-evacuation",title:"An evacuation instruction",level:"B1+",text:"Un départ de feu a été signalé dans le bâtiment. Veuillez quitter les lieux calmement par la sortie de secours la plus proche. N’utilisez pas les ascenseurs. Suivez les indications du personnel et rejoignez le point de rassemblement sur le parking nord.",questions:[q("Main idea","Why must people leave?",["Closing time","A fire has been reported","A sale is starting"],1),q("Action","What must they avoid?",["Stairs","Staff directions","Elevators"],2),q("Details","Where is the meeting point?",["North parking lot","Main entrance","South parking lot"],0)]},
 {id:"shop-checkouts",title:"Which checkout is open?",level:"B1",text:"Chers clients, les caisses automatiques sont momentanément indisponibles. Pour régler vos achats, merci de vous présenter aux caisses trois et quatre. La caisse quatre accepte uniquement les paiements par carte. Pour payer en espèces, veuillez utiliser la caisse trois.",questions:[q("Main idea","What is unavailable?",["All checkouts","Self-service checkouts","Card payments"],1),q("Action","Where should a cash customer go?",["Checkout three","Checkout four","Any self-service checkout"],0),q("Details","What does checkout four accept?",["Cash only","Cards and cash","Cards only"],2)]},
 {id:"train-delay",title:"A delayed departure",level:"B1",text:"Le train à destination de Lyon, initialement prévu à quatorze heures dix, partira avec un retard de vingt minutes. Il desservira les mêmes gares que prévu. Nous vous invitons à rester à proximité des panneaux d’affichage pour suivre les informations concernant votre départ.",questions:[q("Details","How long is the delay?",["Ten minutes","Twenty minutes","Forty minutes"],1),q("Details","What happens to the stops?",["They remain unchanged","One is removed","The train becomes direct"],0),q("Action","Where should passengers check updates?",["At the café","On display boards","Only on the train"],1)]},
 {id:"train-platform",title:"A change of platform",level:"B1+",text:"Attention, changement de voie. Le train pour Bordeaux annoncé voie six partira finalement voie neuf. Les voyageurs sont priés de rejoindre la voie neuf en empruntant le passage souterrain. Le départ est maintenu à seize heures vingt. Merci de ne pas traverser les voies.",questions:[q("Details","What is the new platform?",["Six","Twenty","Nine"],2),q("Action","How should passengers reach it?",["Use the underpass","Cross the tracks","Stay at platform six"],0),q("Details","Has departure time changed?",["Yes, twenty minutes later","No, it stays 16:20","Yes, nine minutes later"],1)]},
 {id:"train-cancelled",title:"A cancelled train",level:"B1+",text:"En raison d’un incident technique, le train de dix-huit heures à destination de Rouen est supprimé. Vos billets sont valables sans supplément dans le prochain train, prévu à dix-neuf heures quinze. Si vous renoncez à votre voyage, adressez-vous au guichet pour connaître les modalités de remboursement.",questions:[q("Main idea","What happened to the 18:00 train?",["It changed platform","It was cancelled","It is boarding"],1),q("Details","When is the next train?",["18:15","19:00","19:15"],2),q("Action","What can the existing ticket be used for?",["The next train without extra charge","Only a refund","A bus with a supplement"],0)]},
 {id:"airport-gate",title:"Your gate has changed",level:"B1",text:"Les passagers du vol à destination de Stockholm sont informés d’un changement de porte. L’embarquement aura lieu porte B douze, et non porte B deux. Il commencera dans quinze minutes. Veuillez préparer votre carte d’embarquement et votre pièce d’identité.",questions:[q("Details","Which gate should passengers use?",["B2","B12","B15"],1),q("Details","When does boarding begin?",["Now","In twelve minutes","In fifteen minutes"],2),q("Action","What should be ready?",["Boarding pass and identification","A cash payment","Checked baggage"],0)]},
 {id:"airport-final",title:"A final boarding call",level:"B1+",text:"Dernier appel pour les passagers du vol à destination de Nice. Veuillez vous présenter immédiatement porte A sept. La porte fermera dans trois minutes. Les bagages de cabine volumineux seront placés en soute gratuitement. Gardez vos médicaments et vos documents avec vous.",questions:[q("Action","When should passengers go to the gate?",["Immediately","In seven minutes","After collecting luggage"],0),q("Details","What happens to bulky cabin bags?",["A fee is charged","They go in the hold free","They are refused"],1),q("Action","What should passengers keep with them?",["All large bags","Only clothes","Medicines and documents"],2)]},
 {id:"museum-closing",title:"The museum is closing",level:"B1",text:"Mesdames et messieurs, les salles d’exposition fermeront dans quinze minutes. La boutique restera ouverte jusqu’à dix-huit heures. Nous vous remercions de rejoindre progressivement le hall principal. N’oubliez pas de récupérer vos affaires au vestiaire avant de sortir.",questions:[q("Details","When do exhibition rooms close?",["In fifteen minutes","At 15:00","In an hour"],0),q("Action","Where should visitors go?",["The roof","The main hall","The café terrace"],1),q("Action","What should be collected?",["Tickets for tomorrow","A free book","Belongings from the cloakroom"],2)]},
 {id:"museum-exit",title:"A different way out",level:"B1+",text:"La sortie donnant sur la rue du Musée est temporairement fermée pour travaux. Pour quitter le bâtiment, veuillez suivre les flèches bleues jusqu’à la cour intérieure. Une sortie accessible aux personnes à mobilité réduite se trouve à droite de l’accueil. Notre équipe est à votre disposition pour vous accompagner.",questions:[q("Main idea","Why is one exit closed?",["Road traffic","Building work","A private party"],1),q("Action","Which signs lead to the courtyard?",["Red arrows","Green numbers","Blue arrows"],2),q("Details","Where is the accessible exit?",["Right of reception","Upstairs","Left of the shop"],0)]},
 {id:"restaurant-number",title:"Your order is ready",level:"B1",text:"La commande numéro quarante-deux est prête. Merci de venir la chercher au comptoir de retrait, à gauche de la caisse. Pour les boissons chaudes, attendez l’appel de votre numéro au second comptoir. Elles ne sont pas remises avec le plateau-repas.",questions:[q("Details","Which order is ready?",["Twenty-four","Forty-two","Fourteen"],1),q("Action","Where is food collected?",["Left of the till","At the table","Outside"],0),q("Action","How are hot drinks collected?",["With the meal tray","By asking another customer","At a second counter when called"],2)]},
 {id:"restaurant-service",title:"The kitchen closes first",level:"B1+",text:"Nous vous informons que la cuisine fermera à vingt et une heures trente. Vous pouvez encore commander un plat pendant dix minutes. Les desserts et les boissons resteront disponibles jusqu’à vingt-deux heures. Merci de passer vos dernières commandes de plats auprès de votre serveur.",questions:[q("Details","How long remains to order a main dish?",["Thirty minutes","Ten minutes","An hour"],1),q("Details","What remains available until 22:00?",["All main dishes","Breakfast","Desserts and drinks"],2),q("Action","Who takes the last main-dish orders?",["Your server","The cashier only","The kitchen directly"],0)]},
];
