export const frenchDictations=[
 {id:"fr-table",text:"Vous pourriez vous installer près de la fenêtre ?",meaning:"Could you sit near the window?",focus:"Polite requests",hint:"Listen for the request, then the new location."},
 {id:"fr-cash",text:"Le distributeur ne prend que les espèces.",meaning:"The machine only takes cash.",focus:"Restrictions",hint:"Ne… que means only, not a negative instruction."},
 {id:"fr-milk",text:"On n’a plus de lait d’avoine, mais il reste du soja.",meaning:"We have no oat milk left, but there is still soy milk.",focus:"Unavailable items",hint:"Notice the contrast between plus de and il reste."},
 {id:"fr-time",text:"Le petit-déjeuner est servi jusqu’à dix heures et demie.",meaning:"Breakfast is served until half past ten.",focus:"Times",hint:"Catch the boundary word jusqu’à, then the time."},
 {id:"fr-price",text:"Ça vous fera douze euros quatre-vingts, s’il vous plaît.",meaning:"That will be €12.80, please.",focus:"Prices",hint:"The amount has both euros and cents."},
 {id:"fr-platform",text:"Le train partira voie neuf, et non voie six.",meaning:"The train will leave from platform nine, not six.",focus:"Changed details",hint:"Et non cancels the second platform."},
 {id:"fr-link",text:"Vous avez une autre table à l’intérieur ?",meaning:"Do you have another table inside?",focus:"Connected speech",hint:"Listen to how vous avez and une autre connect across word boundaries."},
 {id:"fr-repair",text:"Pardon, vous avez dit quinze ou cinquante ?",meaning:"Sorry, did you say fifteen or fifty?",focus:"Clarification",hint:"Hear the two alternatives before choosing an interpretation."},
];
export type ServiceStep={line:string;meaning:string;choices:{text:string;reply:string;correct:boolean}[]};
export const frenchMissions:{id:string;title:string;goal:string;steps:ServiceStep[]}[]=[
 {id:"fr-cafe-mission",title:"Coffee, with a complication",goal:"Choose a substitute, handle payment, and confirm where to collect it.",steps:[
  {line:"Désolée, on n’a plus de lait d’avoine. Du lait de soja, ça vous irait ?",meaning:"There is no oat milk. Would soy milk work?",choices:[{text:"Oui, du soja, c’est très bien.",reply:"Très bien, un café au lait de soja.",correct:true},{text:"Non merci, je prendrai un café noir.",reply:"D’accord, un café noir alors.",correct:true},{text:"Je voudrais réserver pour demain.",reply:"Nous parlons du lait pour votre café. Choisissez une alternative.",correct:false}]},
  {line:"Le terminal est en panne. Vous pouvez régler en espèces ?",meaning:"The card terminal is broken. Can you pay cash?",choices:[{text:"Oui, voici dix euros.",reply:"Merci, je vous rends la monnaie.",correct:true},{text:"Je n’ai pas d’espèces. Où est le distributeur le plus proche ?",reply:"Il y en a un juste en face. Je garde votre commande.",correct:true},{text:"Au lait d’avoine, s’il vous plaît.",reply:"La question porte maintenant sur le paiement.",correct:false}]},
  {line:"Je vous appellerai quand ce sera prêt. Vous pourrez le récupérer au comptoir du fond.",meaning:"I’ll call when it is ready. Collect it at the back counter.",choices:[{text:"Au comptoir du fond, c’est bien ça ?",reply:"Oui, exactement. À tout de suite !",correct:true},{text:"Je vais attendre à l’entrée de la gare.",reply:"Votre café sera au comptoir du fond, dans le café.",correct:false},{text:"D’accord, j’attends votre appel.",reply:"Parfait, ce ne sera pas long.",correct:true}]},
 ]},
 {id:"fr-dinner-mission",title:"A table change at dinner",goal:"Understand the move and make sure your meal follows you.",steps:[
  {line:"Cette table est réservée dans dix minutes. Pourriez-vous passer près de la fenêtre ?",meaning:"This table is reserved in ten minutes. Could you move by the window?",choices:[{text:"Bien sûr. Vous pouvez nous montrer laquelle ?",reply:"Oui, celle-ci, juste à votre droite.",correct:true},{text:"Je voudrais payer en dollars.",reply:"Il s’agit de changer de table, pas de payer.",correct:false},{text:"D’accord, la table près de la fenêtre.",reply:"Exactement, merci beaucoup.",correct:true}]},
  {line:"Laissez vos assiettes ici, je vais les déplacer. Prenez simplement vos affaires.",meaning:"Leave the plates; I’ll move them. Take your belongings.",choices:[{text:"Merci, je prends mon sac.",reply:"Je vous apporte les assiettes tout de suite.",correct:true},{text:"Je porte toutes les assiettes moi-même.",reply:"Je m’occupe des assiettes. Prenez seulement vos affaires.",correct:false},{text:"Pardon, vous vous occupez des assiettes ?",reply:"Oui, ne vous inquiétez pas.",correct:true}]},
  {line:"Pour le dessert, il ne reste plus de tarte. On a encore de la mousse au chocolat.",meaning:"The tart is sold out; chocolate mousse is available.",choices:[{text:"La mousse au chocolat, alors, merci.",reply:"Avec plaisir, je vous l’apporte.",correct:true},{text:"La tarte uniquement, vous venez de dire qu’il en reste.",reply:"La tarte est épuisée. La mousse reste disponible.",correct:false},{text:"Non merci, juste l’addition, s’il vous plaît.",reply:"Bien sûr, je vous apporte l’addition.",correct:true}]},
 ]},
];
