import type { Passage } from "./passages";

const speaker = { name: "Camille et Hugo", age: 30, location: "Paris", voice: "marin", initials: "CH" };
type Lesson = { id:string; title:string; level:Passage["level"]; topic:string; lines:string[]; decode:string; translation:string; phrase:string; meaning:string; points:string[] };
const lessons: Lesson[] = [
 {id:"cafe-rupture",title:"Plus de café filtre",level:"B1",topic:"Coffee",lines:["Bonjour, je voudrais un grand café filtre, s’il vous plaît.","Je suis désolée, on n’a plus de café filtre pour le moment. Je peux vous proposer un allongé.","C’est la même chose ?","Pas tout à fait : c’est un espresso avec de l’eau chaude. Sinon, le prochain café filtre sera prêt dans dix minutes.","Dans ce cas, je vais attendre. Je peux m’installer ici ?","Bien sûr. Je vous l’apporte dès qu’il est prêt."],decode:"On n’a plus de café filtre pour le moment.",translation:"We’re out of filter coffee at the moment.",phrase:"on n’a plus de",meaning:"we’re out of / we no longer have",points:["Filter coffee is unavailable now","An allongé is offered instead","Fresh filter coffee takes ten minutes","The customer chooses to wait"]},
 {id:"cafe-lait",title:"Quel lait reste-t-il ?",level:"B1",topic:"Coffee",lines:["Un latte au lait d’avoine, s’il vous plaît.","On vient de finir la dernière bouteille. Il nous reste du lait de soja ou du lait classique.","Le soja, ça me va. Il y a un supplément ?","Oui, cinquante centimes. Et vous le voulez chaud ou glacé ?","Chaud, merci. Sans sucre.","Très bien : un latte chaud au soja, sans sucre."],decode:"Il nous reste du lait de soja.",translation:"We still have some soy milk left.",phrase:"il nous reste",meaning:"we still have … left",points:["Oat milk has run out","Soy and regular milk remain","Soy costs fifty cents extra","The customer wants a hot unsweetened soy latte"]},
 {id:"cafe-service",title:"Sur place ou à emporter ?",level:"B1",topic:"Coffee",lines:["Bonjour, deux cappuccinos, s’il vous plaît.","Sur place ou à emporter ?","Sur place. On peut s’asseoir en terrasse ?","Oui, mais dans ce cas, commandez directement auprès de ma collègue dehors. Ici, c’est uniquement pour les commandes à emporter.","Ah, d’accord. On ne paie pas ici, alors ?","Non, elle prendra votre commande et vous réglerez avec elle."],decode:"Ici, c’est uniquement pour les commandes à emporter.",translation:"Here, it’s only for takeaway orders.",phrase:"auprès de ma collègue",meaning:"with / through my colleague",points:["The customers want to sit outside","The counter handles takeaway only","They must order from the colleague outside","They will also pay that colleague"]},
 {id:"cafe-especes",title:"La machine ne prend pas la carte",level:"B1+",topic:"Coffee",lines:["Excusez-moi, la machine refuse ma carte. Elle est en panne ?","Non, celle-ci fonctionne seulement avec des pièces. Elle ne prend ni les cartes ni les billets.","Je n’ai qu’un billet de cinq euros. Vous pouvez me faire de la monnaie ?","Je suis désolée, pas aujourd’hui. Mais vous pouvez commander votre café au comptoir et payer par carte.","Même pour un seul café ?","Oui, au comptoir il n’y a pas de minimum."],decode:"Elle ne prend ni les cartes ni les billets.",translation:"It accepts neither cards nor banknotes.",phrase:"faire de la monnaie",meaning:"to give change / break a note",points:["The machine works but accepts coins only","It does not accept notes or cards","The customer cannot get change","The counter accepts a card for one coffee"]},
 {id:"matin-service",title:"Le petit-déjeuner est terminé",level:"B1",topic:"Breakfast",lines:["On voudrait deux petits-déjeuners complets, s’il vous plaît.","Je suis désolée, on sert cette formule jusqu’à onze heures. Il est onze heures et quart.","Même si on ne prend pas les œufs ?","La formule n’est plus disponible, mais vous pouvez commander une tartine et une boisson séparément.","D’accord, deux tartines et deux cafés, alors.","Très bien. Vous souhaitez du beurre et de la confiture ?"],decode:"Vous pouvez commander une tartine et une boisson séparément.",translation:"You can order toast and a drink separately.",phrase:"jusqu’à onze heures",meaning:"until eleven o’clock",points:["Breakfast set meals end at eleven","It is eleven fifteen","Toast and drinks can be ordered separately","They choose two toasts and two coffees"]},
 {id:"matin-croissants",title:"Le dernier croissant",level:"B1",topic:"Breakfast",lines:["Bonjour, vous avez encore deux croissants ?","Il ne m’en reste qu’un. Par contre, j’ai des pains au chocolat qui sortent du four.","Alors, un croissant et un pain au chocolat. Ils sont au même prix ?","Non, le pain au chocolat coûte vingt centimes de plus.","Pas de souci. Vous pouvez les mettre dans deux sacs différents ?","Bien sûr. Attention, le pain au chocolat est encore très chaud."],decode:"Il ne m’en reste qu’un.",translation:"I only have one left.",phrase:"qui sortent du four",meaning:"fresh out of the oven",points:["Only one croissant remains","Fresh pains au chocolat are available","A pain au chocolat costs twenty cents more","The customer asks for separate bags"]},
 {id:"matin-formule",title:"Qu’est-ce qui est compris ?",level:"B1+",topic:"Breakfast",lines:["Dans la formule à neuf euros, le jus d’orange est compris ?","Oui, avec une boisson chaude et une viennoiserie.","Je peux prendre un chocolat chaud à la place du café ?","Bien sûr. En revanche, si vous prenez un jus pressé, il y a deux euros de supplément.","Je garde le jus normal, alors, avec un chocolat chaud et un croissant.","Parfait. Vous pouvez choisir une table, je vous apporte le plateau."],decode:"En revanche, il y a deux euros de supplément.",translation:"However, there’s a two-euro supplement.",phrase:"à la place du café",meaning:"instead of coffee",points:["The nine-euro meal includes juice, a hot drink, and a pastry","Hot chocolate can replace coffee","Freshly squeezed juice costs two euros extra","The customer keeps the ordinary juice"]},
 {id:"matin-comptoir",title:"On règle où ?",level:"B1",topic:"Breakfast",lines:["Excusez-moi, on pourrait avoir l’addition ?","Oui, mais le règlement se fait au comptoir, près de l’entrée.","On vous laisse le plateau sur la table ?","Oui, ne vous inquiétez pas, je m’en occupe. Dites simplement votre numéro de table à ma collègue.","C’est la table douze, c’est ça ?","Exactement. Vous pouvez payer ensemble ou séparément."],decode:"Le règlement se fait au comptoir.",translation:"Payment is made at the counter.",phrase:"je m’en occupe",meaning:"I’ll take care of it",points:["Payment is at the counter near the entrance","They can leave the tray","They should give table number twelve","They may pay together or separately"]},
 {id:"diner-deplacer",title:"Pourriez-vous changer de table ?",level:"B1+",topic:"Dinner",lines:["Excusez-moi de vous déranger. Est-ce que ça vous ennuierait de passer à la table près de la fenêtre ?","Il y a un problème avec celle-ci ?","Non, on doit rapprocher ces deux tables pour un groupe qui arrive. Je peux déplacer vos verres et vos assiettes.","D’accord, tant qu’on reste à l’intérieur.","Oui, c’est juste là, pas en terrasse. Merci beaucoup de votre compréhension.","Pas de problème. On prend nos manteaux et on vous suit."],decode:"Est-ce que ça vous ennuierait de passer à la table près de la fenêtre ?",translation:"Would you mind moving to the table by the window?",phrase:"ça vous ennuierait de",meaning:"would you mind … (a polite request)",points:["Staff politely ask them to change tables","Two tables are needed for an arriving group","The new table is inside by the window","Staff offer to move their plates and glasses"]},
 {id:"diner-reserve",title:"Cette table est réservée",level:"B1+",topic:"Dinner",lines:["Bonsoir, on peut s’installer ici ?","Cette table est réservée à partir de vingt heures. Si vous souhaitez seulement boire un verre, c’est possible.","On voulait dîner. Il est déjà dix-neuf heures trente, ça fait un peu court.","Dans ce cas, j’ai une table pour deux au fond de la salle. Vous pourrez la garder toute la soirée.","Très bien, on préfère celle-là.","Suivez-moi, je vous apporte les cartes."],decode:"Cette table est réservée à partir de vingt heures.",translation:"This table is reserved from eight p.m. onward.",phrase:"ça fait un peu court",meaning:"that doesn’t leave much time",points:["The first table is reserved from eight","It is already seven thirty","The customers want dinner rather than just drinks","They choose a table at the back for the evening"]},
 {id:"diner-rupture",title:"Le plat du jour a changé",level:"B2",topic:"Dinner",lines:["Je vais prendre le poisson du jour avec les légumes.","Malheureusement, il n’y en a plus. Le chef propose du poulet à la place, au même prix.","Je ne mange pas de viande. Vous avez une autre option ?","Oui, le risotto aux champignons peut être préparé sans parmesan. Il faudra compter vingt minutes, parce qu’il est fait à la commande.","Ça me convient. Je préfère attendre.","Très bien. Je précise en cuisine que vous le souhaitez sans parmesan."],decode:"Il faudra compter vingt minutes, parce qu’il est fait à la commande.",translation:"Allow twenty minutes because it’s made to order.",phrase:"au même prix",meaning:"at the same price",points:["The fish is sold out","Chicken is offered at the same price","The customer does not eat meat","They choose mushroom risotto without parmesan and accept a twenty-minute wait"]},
 {id:"diner-paiement",title:"Un seul règlement par carte",level:"B2",topic:"Dinner",lines:["On peut partager l’addition en trois et payer chacun par carte ?","Ce soir, notre terminal a des problèmes de connexion. On ne peut faire qu’un seul règlement par carte pour la table.","Et si l’un de nous paie sa part en espèces ?","Ça, c’est possible. Je déduis les espèces, puis je passe le reste sur une seule carte.","D’accord. Voici vingt euros en espèces, et mon amie règle le reste.","Merci. Attendez bien la confirmation avant de retirer la carte."],decode:"Je déduis les espèces, puis je passe le reste sur une seule carte.",translation:"I deduct the cash, then charge the rest to one card.",phrase:"régler le reste",meaning:"to pay the remainder",points:["The card terminal has connection problems","Only one card payment is possible for the table","A partial cash payment is allowed","Twenty euros are paid in cash and the friend pays the balance"]},
];

export const servicePassages: Passage[] = lessons.map(lesson => ({
 id:lesson.id,title:lesson.title,level:lesson.level,topic:lesson.topic,xp:40,speaker,
 category:"everyday",releasedAt:"2026-09-30",audioFile:`/audio/passages/${lesson.id}.mp3`,
 text:lesson.lines.join("\n"),dialogue:lesson.lines.map((text,i)=>({role:i%2?"Staff":"Customer",text,voice:i%2?"marin":"cedar"})),
 decode:lesson.decode,translation:lesson.translation,phrase:lesson.phrase,meaning:lesson.meaning,
 challenges:["Polite requests","Practical details","Natural conversation"],comprehensionPoints:lesson.points,
}));
