import type {Announcement} from "./announcements";
// Alternative wording tests transfer of meaning, not recall of one recording.
const scenarios=[
 {id:"table",title:"The table needs to change",language:"fr",level:"B1",variants:["Excusez-moi, cette table est réservée à partir de vingt heures. Est-ce que vous pourriez vous installer à la table près de la fenêtre ? Je vais déplacer vos assiettes.","Je suis désolé, on attend un groupe ici dans dix minutes. Je peux vous proposer la petite table au fond. Ne vous inquiétez pas, je m’occupe de vos plats."],change:"Your current table is needed for a reservation",action:"Move to the table offered by the server",reply:"Bien sûr. Est-ce que vous pouvez nous aider à déplacer nos affaires ?",skill:"changing-tables"},
 {id:"milk",title:"Your usual milk is unavailable",language:"fr",level:"B1",variants:["On n’a plus de lait d’avoine aujourd’hui. Il nous reste du lait de soja, si vous voulez. Sinon, je peux vous faire un café sans lait.","Désolée, notre livraison de lait d’avoine n’est pas arrivée. Vous préférez du lait de soja ou un café noir ?"],change:"Oat milk is unavailable",action:"Choose soy milk or black coffee",reply:"Je vais prendre un café noir, alors. Merci.",skill:"substitutions"},
 {id:"breakfast",title:"Breakfast has finished",language:"fr",level:"B1",variants:["La formule petit-déjeuner s’arrête à dix heures. Par contre, on peut encore vous servir une tartine et une boisson chaude, séparément.","Il est trop tard pour le menu du matin, malheureusement. Mais vous pouvez commander une tartine et un café à la carte."],change:"The breakfast deal is no longer available",action:"Order toast and a hot drink separately",reply:"D’accord. Combien coûtent la tartine et le café séparément ?",skill:"service-hours"},
 {id:"cash",title:"The machine only takes cash",language:"fr",level:"B1",variants:["Pour cette machine, c’est uniquement en espèces. Si vous voulez payer par carte, il faut commander au comptoir.","La carte ne fonctionne pas sur le distributeur. Vous pouvez mettre des pièces, ou venir à la caisse pour régler par carte."],change:"Card payment does not work at the machine",action:"Use cash or pay by card at the counter",reply:"Je préfère payer par carte. Je vais commander au comptoir.",skill:"payment"},
 {id:"sv-cash",title:"Paying for coffee",language:"sv",level:"A1",variants:["Maskinen tar bara kontanter. Du kan betala med kort i kassan.","Vill du betala med kort? Gå till kassan, tack. Här är det bara kontanter."],change:"The machine only takes cash",action:"Go to the checkout to pay by card",reply:"Jag vill betala med kort, tack.",skill:"payment"},
 {id:"sv-milk",title:"There is no oat milk",language:"sv",level:"A1",variants:["Havremjölken är slut. Vill du ha svart kaffe?","Tyvärr har vi ingen havremjölk. Går det bra med svart kaffe?"],change:"Oat milk is unavailable",action:"Decide whether black coffee is okay",reply:"Ja, svart kaffe går bra. Tack!",skill:"substitutions"},
 {id:"sv-repeat",title:"Which table?",language:"sv",level:"A1",variants:["Ditt bord är nummer femton, där borta till vänster.","Du har bord femton. Det är till vänster."],change:"You are directed to table fifteen",action:"Go left, or ask for repetition if unsure",reply:"Förlåt, kan du säga det igen?",skill:"clarification"},
] as const;
export const situations:Announcement[]=scenarios.flatMap(s=>s.variants.map((text,index)=>({id:`situation-${s.id}-${index+1}`,title:`${s.title} · ${index+1}`,level:s.level,language:s.language,category:"situations",text,questions:[
 {skill:s.skill,prompt:"What did the server say?",options:[s.change,"Your order is ready to collect","The whole café is closing"],answer:0},
 {skill:"Action",prompt:"What should you do?",options:["Wait without changing anything",s.action,"Leave immediately"],answer:1},
 {skill:"Response",prompt:"Which response fits?",options:[s.language==="sv"?"Var ligger stationen?":"Où est la gare ?",s.language==="sv"?"Jag heter Anna.":"Il fait beau aujourd’hui.",s.reply],answer:2},
 ].map((q,i)=>{const offset=(index+i+s.id.length)%3;return {...q,options:[...q.options.slice(offset),...q.options.slice(0,offset)],answer:(q.answer-offset+3)%3};})})));
