import type {Passage} from "./passages";
// Short authored A1 exchanges. English scaffolding is separate from the audio.
const lessons=[
 ["hej","Hej! Vad heter du?","Introductions",["Hej! Jag heter Anna. Vad heter du?","Jag heter Erik. Trevligt att träffas!","Var kommer du ifrån?","Jag kommer från Sverige. Och du?","Jag kommer från USA."],"Vad heter du?","What is your name?","Jag heter","My name is",["Anna and Erik introduce themselves","Erik is from Sweden","Anna is from the USA"]],
 ["kaffe","En kaffe, tack","Coffee",["Hej! En kaffe, tack.","Vill du ha mjölk?","Ja, lite mjölk, tack.","Vill du sitta här eller ta med?","Jag tar med."],"Vill du sitta här eller ta med?","Would you like to sit here or take it away?","ta med","take away / bring along",["A coffee is ordered","The customer wants a little milk","The coffee is takeaway"]],
 ["frukost","Frukost på hotellet","Breakfast",["God morgon! Var är frukosten?","Den är på första våningen.","När slutar frukosten?","Klockan tio.","Tack så mycket!"],"När slutar frukosten?","When does breakfast end?","klockan tio","at ten o’clock",["The guest asks where breakfast is","It is on the first floor","Breakfast ends at ten"]],
 ["priset","Vad kostar det?","Shopping",["Ursäkta, vad kostar den här bullen?","Den kostar trettio kronor.","Jag tar två, tack.","Det blir sextio kronor.","Kan jag betala med kort?","Ja, det går bra."],"Kan jag betala med kort?","Can I pay by card?","vad kostar","how much does … cost",["One bun costs thirty kronor","The customer buys two","The total is sixty kronor","Cards are accepted"]],
 ["vagen","Var ligger stationen?","Directions",["Ursäkta, var ligger stationen?","Gå rakt fram och sväng vänster.","Är det långt?","Nej, ungefär fem minuter till fots.","Tack för hjälpen!"],"Gå rakt fram och sväng vänster.","Go straight ahead and turn left.","rakt fram","straight ahead",["The person wants the station","Go straight and turn left","It is about five minutes on foot"]],
 ["bussen","Bussen till centrum","Transport",["Går den här bussen till centrum?","Nej, du ska ta buss nummer fyra.","Var är hållplatsen?","Den är där borta, till höger.","När kommer bussen?","Om tio minuter."],"Du ska ta buss nummer fyra.","You should take bus number four.","om tio minuter","in ten minutes",["This is not the right bus","Bus four goes to the center","The stop is to the right","It arrives in ten minutes"]],
 ["middag","Ett bord för två","Dinner",["Hej! Har ni ett bord för två?","Ja. Vill ni sitta inne eller ute?","Inne, tack.","Varsågoda, här är menyn.","Tack! Kan vi få vatten?","Självklart."],"Har ni ett bord för två?","Do you have a table for two?","kan vi få","could we have",["They need a table for two","They prefer inside","They ask for water"]],
 ["slut","Mjölken är slut","Coffee",["En kaffe med havremjölk, tack.","Tyvärr, havremjölken är slut. Vi har vanlig mjölk.","Då tar jag svart kaffe.","En stor eller en liten?","En liten, tack."],"Tyvärr, havremjölken är slut.","Unfortunately, we’re out of oat milk.","är slut","has run out",["Oat milk is unavailable","Regular milk is available","The customer chooses a small black coffee"]],
 ["oppet","När öppnar ni?","Daily life",["Hej! När öppnar ni i morgon?","Vi öppnar klockan nio.","Och när stänger ni?","Klockan sex på kvällen.","Är det öppet på söndag?","Nej, på söndag har vi stängt."],"På söndag har vi stängt.","We are closed on Sunday.","när öppnar ni","when do you open",["The shop opens at nine tomorrow","It closes at six in the evening","It is closed Sunday"]],
 ["hjalp","Kan du säga det igen?","Clarification",["Du ska gå till rum femton.","Förlåt, jag förstår inte. Kan du säga det igen?","Rum femton. Ett, fem.","Femton?","Ja, precis. Det är på andra våningen.","Tack! Jag lär mig svenska."],"Kan du säga det igen?","Can you say that again?","jag lär mig svenska","I am learning Swedish",["The destination is room fifteen","The listener asks for repetition","The room is on the second floor"]],
 ["affaren","I mataffären","Shopping",["Ursäkta, var finns brödet?","Där borta, bredvid mjölken.","Tack. Har ni äpplen också?","Ja, vid ingången.","Behöver jag en påse?","Du kan köpa en vid kassan."],"Där borta, bredvid mjölken.","Over there, next to the milk.","bredvid","next to",["Bread is next to the milk","Apples are by the entrance","A bag can be bought at the checkout"]],
 ["dagen","Vad gör du i dag?","Daily life",["Vad gör du i dag?","Jag jobbar på morgonen.","Vill du ta en fika efter jobbet?","Ja, gärna. Klockan tre?","Det passar bra. Vi ses på kaféet.","Vi ses!"],"Vill du ta en fika efter jobbet?","Would you like to have a coffee break after work?","efter jobbet","after work",["One person works in the morning","They arrange a fika after work","They will meet at three at the café"]],
] as const;
export const swedishPassages:Passage[]=lessons.map(([id,title,topic,lines,decode,translation,phrase,meaning,points])=>({id:`sv-${id}`,language:"sv",level:"A1",title,topic,xp:40,category:"everyday",releasedAt:"2026-09-30",text:lines.join("\n"),decode,translation,phrase,meaning,comprehensionPoints:[...points],challenges:["Everyday words","Numbers","Swedish rhythm"],speaker:{name:"Anna och Erik",age:30,location:"Stockholm",voice:"marin",initials:"AE"},dialogue:lines.map((text,i)=>({role:i%2?"Erik":"Anna",text,voice:i%2?"cedar":"marin"})),audioFile:`/audio/passages/sv-${id}.mp3`}));
