"use client";
import {useState} from "react";
export type NativeNote={id:string;url:string;title:string;summary:string;createdAt:string};
export default function NativeListening({language,notes,onNotes}:{language:"fr"|"sv";notes:NativeNote[];onNotes:(notes:NativeNote[])=>void}){
 const [url,setUrl]=useState(""),[title,setTitle]=useState(""),[summary,setSummary]=useState(""),[error,setError]=useState("");
 const resources=language==="fr"?[{title:"TV5MONDE · authentic video exercises",url:"https://apprendre.tv5monde.com/fr/collection-all",description:"Choose a B1 or B2 exercise and a topic you enjoy. Listen before reading."}]:[{title:"Radio Sweden på lätt svenska",url:"https://www.sverigesradio.se/radio-sweden-pa-latt-svenska",description:"Human-presented news in easier Swedish. This can be a stretch at A1: start with 10–20 seconds and one familiar detail."}];
 const save=()=>{try{const parsed=new URL(url);if(parsed.protocol!=="https:"||parsed.username||parsed.password)throw Error();onNotes([{id:crypto.randomUUID(),url:parsed.href,title:title.trim(),summary:summary.trim(),createdAt:new Date().toISOString()},...notes].slice(0,50));setUrl("");setTitle("");setSummary("");setError("")}catch{setError("Enter a valid HTTPS link without credentials.")}};
 return <section className="practice-tools"><p className="eyebrow">Original voices · external listening</p><h2>Take your ear into the real world.</h2><p>These recordings stay with their original publishers. We link to them, not copy or relabel them as our own. Availability and captions depend on the publisher.</p><div className="library-grid">{resources.map(r=><article key={r.url}><h3>{r.title}</h3><p>{r.description}</p><a href={r.url} target="_blank" rel="noopener noreferrer">Open original source ↗</a></article>)}</div><ol><li>Listen to a short excerpt without reading. Write the situation and one detail.</li><li>Check the publisher’s transcript or captions; note one phrase you missed.</li><li>Replay, echo the phrase, then retell the meaning without text.</li></ol><p>For a YouTube recording, open <a href="#studio">Studio</a> and paste its video URL to use the full four-step loop. Other publishers open in a separate tab.</p><h3>Your original-media notebook</h3><p>Save your own brief notes, not a copied article or full copyrighted transcript. Entries sync with this language. They do not claim a verified listening score.</p><label>Source URL<input type="url" maxLength={1000} value={url} onChange={e=>setUrl(e.target.value)}/></label><label>Title<input maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>What I understood / phrase to revisit<textarea maxLength={1200} value={summary} onChange={e=>setSummary(e.target.value)}/></label><button disabled={!url.trim()||!title.trim()||!summary.trim()||notes.length>=50} onClick={save}>Save listening note</button>{error&&<p role="alert">{error}</p>}{notes.length>=50&&<p>Your notebook has 50 entries. Remove an older entry to add another.</p>}<ul>{notes.map(n=><li key={n.id}><a href={/^https:\/\//.test(n.url)?n.url:undefined} target="_blank" rel="noopener noreferrer">{n.title}</a><p>{n.summary}</p><button onClick={()=>onNotes(notes.filter(item=>item.id!==n.id))}>Remove note</button></li>)}</ul></section>;
}
