"use client";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { passages, type Passage } from "../content/passages";

const waves=[18,28,15,36,22,44,29,53,34,23,48,31,56,38,26,46,32,52,40,24,35,47,30,42,20,34,25,45,29,38,19,28,16,24,13];
const labels=[{name:"First listen",sub:"Catch the big picture"},{name:"Decode",sub:"Find what you missed"},{name:"Shadow",sub:"Match the speaker"},{name:"Retell",sub:"Make it your own"}];
const SPEECH_CACHE="a-loreille-speech-v1";
const PROGRESS_KEY="a-loreille-progress-v1";
const LATEST_UPDATE={id:"2026-08-26-shadow-coaching",date:"August 26, 2026",title:"Shadowing just got much easier",summary:"Your practice loop now gives you more support while you speak—and clearer guidance afterward.",items:[{mark:"01",title:"French text while you shadow",body:"Follow the complete, line-by-line transcript in built-in lessons and Studio clips."},{mark:"02",title:"More useful speaking feedback",body:"See separate coaching for word accuracy, rhythm, pauses, and a likely liaison to practise."},{mark:"03",title:"A focused replay drill",body:"Every recording now ends with one short phrase and a concrete listen-and-repeat exercise."},{mark:"04",title:"Your private notebook",body:"Use the N in the corner to leave feature ideas or report anything that feels wrong."}]};

type ComprehensionFeedback={score:number;understood:string[];missed:string[];misconception:string|null;listening_target:string};
type SpeakingAttempt={id:string;createdAt:string;task:string;transcript:string;score:number;level:string;summary:string;nextDrill:string};
type FeedbackNote={id:string;createdAt:string;kind:"idea"|"bug";text:string;resolved:boolean};
type CaptionCue={start:number;duration:number;text:string};

function NewUpdates({onClose}:{onClose:()=>void}){
 const closeRef=useRef<HTMLButtonElement|null>(null);
 useEffect(()=>{closeRef.current?.focus();const close=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose()};document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close)},[onClose]);
 return <div className="updates-backdrop" role="presentation"><section className="updates-modal" role="dialog" aria-modal="true" aria-labelledby="updates-title"><button ref={closeRef} className="updates-close" onClick={onClose} aria-label="Close new updates">×</button><div className="updates-ribbon"><span>New</span><time>{LATEST_UPDATE.date}</time></div><p className="eyebrow">What’s new at À l’Oreille</p><h1 id="updates-title">{LATEST_UPDATE.title}</h1><p className="updates-summary">{LATEST_UPDATE.summary}</p><div className="updates-list">{LATEST_UPDATE.items.map(item=><article key={item.mark}><span>{item.mark}</span><div><h2>{item.title}</h2><p>{item.body}</p></div></article>)}</div><button className="updates-primary" onClick={onClose}>Start listening <span>→</span></button><small>You’ll only see this again after the app gets another update.</small></section></div>
}

async function speechCacheKey(text:string,voice:string){
 const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(`french-paris-v1\n${voice}\n${text.trim()}`));
 const hash=Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,"0")).join("");
 return new Request(`${window.location.origin}/api/speech/audio/${hash}`);
}

async function loadSpeech(text:string,audioFile?:string,voice="marin"){
 if(audioFile){const approved=await fetch(audioFile);if(approved.ok)return approved.blob()}
 const canCache="caches" in window;
 const cache=canCache?await caches.open(SPEECH_CACHE).catch(()=>null):null;
 const cacheKey=canCache?await speechCacheKey(text,voice):null;
 const cached=cacheKey?await cache?.match(cacheKey).catch(()=>undefined):null;
 if(cached)return cached.blob();
 const response=await fetch("/api/speech",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,voice})});
 if(!response.ok)throw new Error();
 const blob=await response.blob();
 if(cache&&cacheKey)await cache.put(cacheKey,new Response(blob,{headers:{"Content-Type":"audio/mpeg","Cache-Control":"max-age=2592000"}})).catch(()=>undefined);
 return blob;
}

function getYouTubeId(value:string){
 try{
  const url=new URL(value.trim());
  if(url.hostname==="youtu.be")return url.pathname.slice(1).split("/")[0];
  if(url.hostname.endsWith("youtube.com")){
   if(url.pathname==="/watch")return url.searchParams.get("v");
   const match=url.pathname.match(/^\/(?:shorts|embed|live)\/([^/?]+)/);
   return match?.[1]||null;
  }
 }catch{return null}
 return null;
}

function formatTime(seconds:number){const safe=Number.isFinite(seconds)?Math.max(0,Math.round(seconds)):0;return `${Math.floor(safe/60)}:${String(safe%60).padStart(2,"0")}`}

function ClipTimeline({duration,start,end,onStart,onEnd}:{duration:number;start:number;end:number;onStart:(value:number)=>void;onEnd:(value:number)=>void}){
 const railRef=useRef<HTMLDivElement|null>(null),dragRef=useRef<{x:number;start:number;end:number}|null>(null);
 const maximum=Math.max(10,Math.round(duration||end||60)),minimumGap=Math.min(5,maximum),left=Math.min(100,start/maximum*100),width=Math.max(0,(end-start)/maximum*100);
 const updateStart=(value:number)=>onStart(Math.max(0,Math.min(value,end-minimumGap)));
 const updateEnd=(value:number)=>onEnd(Math.min(maximum,Math.max(value,start+minimumGap)));
 const moveBlock=(nextStart:number)=>{const length=end-start,clamped=Math.max(0,Math.min(maximum-length,nextStart));onStart(clamped);onEnd(clamped+length)};
 const moveDrag=(clientX:number)=>{const drag=dragRef.current,rail=railRef.current;if(!drag||!rail)return;const delta=Math.round((clientX-drag.x)/rail.getBoundingClientRect().width*maximum),length=drag.end-drag.start,nextStart=Math.max(0,Math.min(maximum-length,drag.start+delta));onStart(nextStart);onEnd(nextStart+length)};
 return <section className="clip-editor" aria-label="Choose the video passage"><header><div><span className="eyebrow">Selected passage</span><strong>{formatTime(start)} <i>to</i> {formatTime(end)}</strong></div><em>{formatTime(end-start)} of {formatTime(maximum)}</em></header><div className="range-stage" ref={railRef}><div className="range-rail"/><div className="range-selection" role="slider" tabIndex={0} aria-label="Move selected passage" aria-valuemin={0} aria-valuemax={maximum} aria-valuenow={start} aria-valuetext={`${formatTime(start)} to ${formatTime(end)}`} style={{left:`${left}%`,width:`${width}%`}} onPointerDown={event=>{dragRef.current={x:event.clientX,start,end};event.currentTarget.setPointerCapture(event.pointerId)}} onPointerMove={event=>moveDrag(event.clientX)} onPointerUp={event=>{moveDrag(event.clientX);dragRef.current=null;event.currentTarget.releasePointerCapture(event.pointerId)}} onPointerCancel={()=>{dragRef.current=null}} onKeyDown={event=>{if(event.key!=="ArrowLeft"&&event.key!=="ArrowRight")return;event.preventDefault();moveBlock(start+(event.key==="ArrowRight"?(event.shiftKey?5:1):event.shiftKey?-5:-1))}}><span>Drag to move</span></div><input className="range-input range-start" type="range" min={0} max={maximum} step={1} value={start} onChange={event=>updateStart(Number(event.target.value))} aria-label="Clip start time"/><input className="range-input range-end" type="range" min={0} max={maximum} step={1} value={end} onChange={event=>updateEnd(Number(event.target.value))} aria-label="Clip end time"/></div><div className="range-times"><span>Start · 0:00</span><span>Full video · {formatTime(maximum)}</span></div><div className="clip-editor-footer"><div className="clip-time-fields"><label>Start <input type="number" min={0} max={Math.max(0,end-minimumGap)} value={start} onChange={event=>updateStart(Number(event.target.value))}/><span>sec</span></label><label>End <input type="number" min={start+minimumGap} max={maximum} value={end} onChange={event=>updateEnd(Number(event.target.value))}/><span>sec</span></label></div><div className="clip-presets" aria-label="Clip length">{[30,60,90].map(length=><button key={length} disabled={length>maximum} onClick={()=>onEnd(Math.min(maximum,start+length))}>{length}s</button>)}</div></div><p>Drag the pink passage to move it. Drag either white handle to change its length.</p></section>
}

function Player({passage,playing,onToggle,onReplay,progress,duration}:{passage:Passage;playing:boolean;onToggle:()=>void;onReplay:()=>void;progress:number;duration:number}){
  return <div className="audio-card"><div className="audio-topline"><div className="speaker"><span className="speaker-photo">{passage.speaker.initials}</span><div><strong>{passage.speaker.name}, {passage.speaker.age}</strong><small>Conversation · {passage.speaker.location} · AI voice</small></div></div><span className="speed">French audio</span></div><div className="player"><button className="play" onClick={onToggle} aria-label={playing?"Pause audio":"Play audio"}>{playing?"Ⅱ":"▶"}</button><div className="wave-wrap"><div className="wave" role="progressbar" aria-label="Audio progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(progress)}>{waves.map((h,i)=><i key={i} style={{height:h,background:i/waves.length*100<=progress?"var(--ink)":"var(--line-strong)"}}/>)}</div><div className="time"><span>{formatTime(duration*progress/100)}</span><span>{duration?formatTime(duration):"–:––"}</span></div></div><button className="replay" onClick={onReplay} aria-label="Replay audio from the beginning">↶<small>all</small></button></div></div>
}

function SelectionSaver({saved,onSave}:{saved:string[];onSave:(text:string)=>void}){
 const [capture,setCapture]=useState<{text:string;left:number;top:number}|null>(null),[notice,setNotice]=useState("");
 useEffect(()=>{const inspect=()=>{window.setTimeout(()=>{const selection=window.getSelection();const text=selection?.toString().replace(/\s+/g," ").trim()||"";if(!selection||selection.isCollapsed||text.length<2||text.length>220){setCapture(null);return}const range=selection.getRangeAt(0);const node=range.commonAncestorContainer;const element=(node.nodeType===Node.ELEMENT_NODE?node:node.parentElement) as Element|null;const frenchSurface=".decode-card>p,.full-transcript p,.phrase-note strong,.library-grid h2,.library-grid article>p,.daily-note h2,.passage strong,.session-rail h2,.studio-transcript>p";if(!element?.closest(frenchSurface)){setCapture(null);return}const rect=range.getBoundingClientRect();setCapture({text,left:Math.min(window.innerWidth-150,Math.max(12,rect.left+rect.width/2-62)),top:Math.max(12,rect.top-48)})},0)};document.addEventListener("mouseup",inspect);document.addEventListener("touchend",inspect);return()=>{document.removeEventListener("mouseup",inspect);document.removeEventListener("touchend",inspect)}},[]);
 const save=()=>{if(!capture)return;if(saved.includes(capture.text)){setNotice("Already in your notebook");setCapture(null);return}onSave(capture.text);setNotice("Saved for review");window.getSelection()?.removeAllRanges();setCapture(null);window.setTimeout(()=>setNotice(""),2200)};
 return <>{capture&&<button className="selection-save" style={{left:capture.left,top:capture.top}} onMouseDown={event=>event.preventDefault()} onClick={save}><span>＋</span> Save phrase</button>}{notice&&<div className="save-notice" role="status">{notice}</div>}</>
}

function FeedbackNotebook({notes,onAdd,onToggle,onRemove}:{notes:FeedbackNote[];onAdd:(kind:FeedbackNote["kind"],text:string)=>void;onToggle:(id:string)=>void;onRemove:(id:string)=>void}){
 const [open,setOpen]=useState(false),[kind,setKind]=useState<FeedbackNote["kind"]>("idea"),[text,setText]=useState("");
 const panelRef=useRef<HTMLDivElement|null>(null),buttonRef=useRef<HTMLButtonElement|null>(null),textareaRef=useRef<HTMLTextAreaElement|null>(null);
 useEffect(()=>{if(!open)return;textareaRef.current?.focus();const close=(event:KeyboardEvent)=>{if(event.key==="Escape"){setOpen(false);buttonRef.current?.focus()}};const outside=(event:MouseEvent)=>{if(!panelRef.current?.contains(event.target as Node)&&!buttonRef.current?.contains(event.target as Node))setOpen(false)};document.addEventListener("keydown",close);document.addEventListener("mousedown",outside);return()=>{document.removeEventListener("keydown",close);document.removeEventListener("mousedown",outside)}},[open]);
 const save=()=>{const clean=text.trim();if(!clean)return;onAdd(kind,clean);setText("")};
 return <div className="profile-notebook"><button ref={buttonRef} className="avatar" aria-label="Open Nikki’s ideas and bug notes" aria-expanded={open} aria-controls="feedback-notebook" onClick={()=>setOpen(value=>!value)}>N{notes.some(note=>!note.resolved)&&<span className="note-dot"/>}</button>{open&&<section ref={panelRef} id="feedback-notebook" className="feedback-notebook" aria-label="Ideas and bug notes"><header><div><p className="eyebrow">Nikki’s notebook</p><h2>Leave a note for the app.</h2></div><button className="notebook-close" onClick={()=>setOpen(false)} aria-label="Close notebook">×</button></header><p className="notebook-intro">Jot down anything confusing, broken, or worth adding. It saves privately with your progress.</p><div className="note-kind" aria-label="Note type">{(["idea","bug"] as const).map(value=><button key={value} className={kind===value?"selected":""} aria-pressed={kind===value} onClick={()=>setKind(value)}>{value==="idea"?"✦ Feature idea":"◇ Report a bug"}</button>)}</div><label htmlFor="feedback-note">What should we remember?</label><textarea ref={textareaRef} id="feedback-note" value={text} maxLength={600} onChange={event=>setText(event.target.value)} placeholder={kind==="idea"?"I wish the app could…":"I was trying to… but instead…"}/><div className="note-compose-footer"><span>{text.length}/600</span><button onClick={save} disabled={!text.trim()}>Save note</button></div><div className="note-list" aria-live="polite">{notes.length?<>{notes.map(note=><article key={note.id} className={note.resolved?"resolved":""}><div><span className={`note-badge ${note.kind}`}>{note.kind==="idea"?"Idea":"Bug"}</span><time dateTime={note.createdAt}>{new Date(note.createdAt).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</time></div><p>{note.text}</p><footer><button onClick={()=>onToggle(note.id)}>{note.resolved?"Reopen":"Mark handled"}</button><button onClick={()=>onRemove(note.id)} aria-label={`Delete note: ${note.text}`}>Delete</button></footer></article>)}</>:<div className="note-empty"><span>✎</span><p>No notes yet. The first one can be as rough as a sticky note.</p></div>}</div></section>}</div>
}

function AccessGate({children}:{children:ReactNode}){
 const [state,setState]=useState<"checking"|"allowed"|"signed-out"|"denied">("checking");
 useEffect(()=>{fetch("/api/session",{cache:"no-store"}).then(response=>{if(response.ok)setState("allowed");else if(response.status===403)setState("denied");else setState("signed-out")}).catch(()=>setState("signed-out"))},[]);
 if(state==="allowed")return <>{children}</>;
 return <main className="access-page"><section className="access-card"><div className="access-mark">à</div><p className="eyebrow">À l’Oreille · Private listening room</p>{state==="checking"?<><h1>Opening your French notebook…</h1><p className="access-copy">One quiet moment while we check your invitation.</p><div className="access-loading" aria-label="Checking access"><span/><span/><span/></div></>:state==="signed-out"?<><h1>Bienvenue, Nikki.</h1><p className="access-copy">Sign in with the ChatGPT account that received your invitation. Your lessons, saved phrases, and notes will follow you between devices.</p><a className="access-primary" href="/signin-with-chatgpt?return_to=%2F">Continue with ChatGPT <span>→</span></a><small>Only invited accounts can enter or use the app’s AI voice and coaching.</small></>:<><h1>This account isn’t on the guest list.</h1><p className="access-copy">Sign out, then continue with the ChatGPT account Nikki uses at the invited email address.</p><a className="access-primary" href="/signout-with-chatgpt?return_to=%2F">Switch ChatGPT account <span>→</span></a><small>If this still appears, ask Christopher to check the invited email.</small></>}</section></main>
}

function Home(){
 const [view,setView]=useState<"today"|"practice"|"library"|"studio"|"about">("today"),[step,setStep]=useState(0),[playing,setPlaying]=useState(false),[progress,setProgress]=useState(0),[duration,setDuration]=useState(0),[text,setText]=useState(""),[recording,setRecording]=useState(false),[done,setDone]=useState(false);
 const [reviewOrigin,setReviewOrigin]=useState(false),[reviewNotice,setReviewNotice]=useState("");
 const [youtubeUrl,setYoutubeUrl]=useState(""),[videoId,setVideoId]=useState<string|null>(null),[clipStart,setClipStart]=useState(0),[clipEnd,setClipEnd]=useState(60),[urlError,setUrlError]=useState("");
 const [passageId,setPassageId]=useState("cafe"),[xp,setXp]=useState(420),[completed,setCompleted]=useState<string[]>([]),[savedPhrases,setSavedPhrases]=useState<string[]>([]),[phraseReviews,setPhraseReviews]=useState<Record<string,string>>({}),[speakingAttempts,setSpeakingAttempts]=useState<SpeakingAttempt[]>([]),[feedbackNotes,setFeedbackNotes]=useState<FeedbackNote[]>([]),[lastSeenUpdateId,setLastSeenUpdateId]=useState(""),[practiceDates,setPracticeDates]=useState<string[]>([]),[reviews,setReviews]=useState<Record<string,string>>({}),[reviewRatings,setReviewRatings]=useState<Record<string,string>>({}),[listeningPatterns,setListeningPatterns]=useState<Record<string,number>>({}),[diagnosis,setDiagnosis]=useState<string[]>([]),[assessment,setAssessment]=useState<ComprehensionFeedback|null>(null),[assessing,setAssessing]=useState(false),[assessmentError,setAssessmentError]=useState(""),[progressLoaded,setProgressLoaded]=useState(false),[syncState,setSyncState]=useState<"local"|"syncing"|"synced">("local"),[voiceError,setVoiceError]=useState("");const audioRef=useRef<HTMLAudioElement|null>(null),audioUrlRef=useRef("");const passage=passages.find(p=>p.id===passageId)!;
 useEffect(()=>{const apply=(data:any)=>{if(typeof data?.xp==="number")setXp(data.xp);if(Array.isArray(data?.completed))setCompleted(data.completed);if(Array.isArray(data?.savedPhrases))setSavedPhrases(data.savedPhrases);if(data?.phraseReviews&&typeof data.phraseReviews==="object")setPhraseReviews(data.phraseReviews);if(Array.isArray(data?.speakingAttempts))setSpeakingAttempts(data.speakingAttempts.slice(0,30));if(Array.isArray(data?.feedbackNotes))setFeedbackNotes(data.feedbackNotes.slice(0,100));if(typeof data?.lastSeenUpdateId==="string")setLastSeenUpdateId(data.lastSeenUpdateId);if(Array.isArray(data?.practiceDates))setPracticeDates(data.practiceDates);if(data?.reviews&&typeof data.reviews==="object")setReviews(data.reviews);if(data?.reviewRatings&&typeof data.reviewRatings==="object")setReviewRatings(data.reviewRatings);if(data?.listeningPatterns&&typeof data.listeningPatterns==="object")setListeningPatterns(data.listeningPatterns)};try{const saved=localStorage.getItem(PROGRESS_KEY);if(saved)apply(JSON.parse(saved))}catch{}fetch("/api/progress").then(response=>response.ok?response.json():null).then(data=>{if(data?.state){apply(data.state);setSyncState("synced")}}).catch(()=>undefined).finally(()=>setProgressLoaded(true))},[]);
 useEffect(()=>{if(!progressLoaded)return;const state={xp,completed,savedPhrases,phraseReviews,speakingAttempts,feedbackNotes,lastSeenUpdateId,practiceDates,reviews,reviewRatings,listeningPatterns};try{localStorage.setItem(PROGRESS_KEY,JSON.stringify(state))}catch{}setSyncState("syncing");const timer=window.setTimeout(()=>fetch("/api/progress",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(state)}).then(response=>{if(response.ok)setSyncState("synced");else setSyncState("local")}).catch(()=>setSyncState("local")),700);return()=>window.clearTimeout(timer)},[xp,completed,savedPhrases,phraseReviews,speakingAttempts,feedbackNotes,lastSeenUpdateId,practiceDates,reviews,reviewRatings,listeningPatterns,progressLoaded]);
 useEffect(()=>()=>{audioRef.current?.pause();if(audioUrlRef.current)URL.revokeObjectURL(audioUrlRef.current)},[]);
 const clearAudio=()=>{audioRef.current?.pause();audioRef.current=null;if(audioUrlRef.current)URL.revokeObjectURL(audioUrlRef.current);audioUrlRef.current="";setPlaying(false);setDuration(0)};
 const toggleSample=async()=>{if(audioRef.current){if(playing){audioRef.current.pause();setPlaying(false)}else{if(audioRef.current.ended)audioRef.current.currentTime=0;await audioRef.current.play();setPlaying(true)}return}setVoiceError("");setPlaying(true);try{const url=URL.createObjectURL(await loadSpeech(passage.text,passage.audioFile,passage.speaker.voice));audioUrlRef.current=url;const audio=new Audio(url);audioRef.current=audio;audio.onloadedmetadata=()=>setDuration(audio.duration);audio.ontimeupdate=()=>setProgress(audio.duration?audio.currentTime/audio.duration*100:0);audio.onended=()=>{setPlaying(false);setProgress(100)};audio.onerror=()=>{setPlaying(false);setVoiceError("The natural voice is temporarily unavailable.")};await audio.play()}catch{clearAudio();setVoiceError("The natural voice is temporarily unavailable.")}};
 const replaySample=()=>{const audio=audioRef.current;if(!audio){void toggleSample();return}audio.currentTime=0;setProgress(0);void audio.play().then(()=>setPlaying(true)).catch(()=>setVoiceError("The natural voice is temporarily unavailable."))};
 const scheduleReview=(id:string,rating:"Again"|"Hard"|"Good"|"Easy")=>{const days={Again:0,Hard:1,Good:3,Easy:7}[rating];setReviews(items=>({...items,[id]:new Date(Date.now()+days*86400000).toISOString()}));setReviewRatings(items=>({...items,[id]:rating}))};
 const schedulePhrase=(phrase:string,rating:"Again"|"Hard"|"Good"|"Easy")=>{const days={Again:0,Hard:1,Good:3,Easy:7}[rating];setPhraseReviews(items=>({...items,[phrase]:new Date(Date.now()+days*86400000).toISOString()}))};
 const rememberSpeaking=(attempt:SpeakingAttempt)=>setSpeakingAttempts(items=>[attempt,...items].slice(0,30));
 const exportProgress=()=>{const state={xp,completed,savedPhrases,phraseReviews,speakingAttempts,feedbackNotes,lastSeenUpdateId,practiceDates,reviews,reviewRatings,listeningPatterns};const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download=`a-loreille-backup-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url)};
 const advance=()=>{audioRef.current?.pause();setPlaying(false);if(step<3){setStep(step+1)}else{const today=new Date().toISOString().slice(0,10);const firstCompletion=!completed.includes(passage.id);setDone(true);if(firstCompletion)setXp(x=>x+passage.xp);setCompleted(items=>items.includes(passage.id)?items:[...items,passage.id]);setPracticeDates(items=>items.includes(today)?items:[...items,today]);scheduleReview(passage.id,"Good");if(diagnosis.length)setListeningPatterns(items=>{const next={...items};diagnosis.filter(item=>item!=="I understood it").forEach(item=>next[item]=(next[item]||0)+1);return next})}};
 const assessUnderstanding=async()=>{setAssessing(true);setAssessmentError("");try{const response=await fetch("/api/comprehension",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({summary:text,passage:passage.text,level:passage.level})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Feedback is unavailable.");setAssessment(data)}catch(error){setAssessmentError(error instanceof Error?error.message:"Feedback is unavailable.")}finally{setAssessing(false)}};
 const handlePrimary=()=>{if(step===0&&!assessment){void assessUnderstanding();return}advance()};
 const toggleSavedPhrase=()=>setSavedPhrases(items=>items.includes(passage.phrase)?items.filter(item=>item!==passage.phrase):[...items,passage.phrase]);
 const streak=practiceDates.length;
 const dueCount=Object.values(reviews).filter(date=>new Date(date)<=new Date()).length;
 const loadVideo=()=>{const id=getYouTubeId(youtubeUrl);if(!id){setUrlError("Paste a valid YouTube video, Short, or youtu.be link.");return}setVideoId(id);setUrlError("")};
 return <main className="app-shell">{progressLoaded&&lastSeenUpdateId!==LATEST_UPDATE.id&&<NewUpdates onClose={()=>setLastSeenUpdateId(LATEST_UPDATE.id)}/>}<SelectionSaver saved={savedPhrases} onSave={phrase=>setSavedPhrases(items=>items.includes(phrase)?items:[...items,phrase])}/><header className="topbar"><button className="brand" onClick={()=>setView("today")}><span className="brand-mark">à</span><span>À l’Oreille</span></button><nav aria-label="Main navigation">{(["today","library","studio","about"] as const).map(item=>{const active=view===item||(item==="today"&&view==="practice");return <button key={item} className={active?"active":""} aria-current={active?"page":undefined} onClick={()=>{clearAudio();setView(item)}}>{item[0].toUpperCase()+item.slice(1)}</button>})}</nav><div className="header-actions"><div className="xp-pill"><strong>{xp} XP</strong><span>toward B2 mastery</span></div><div className="streak"><span>◆</span> {streak} practice {streak===1?"day":"days"}</div><FeedbackNotebook notes={feedbackNotes} onAdd={(kind,note)=>setFeedbackNotes(items=>[{id:crypto.randomUUID(),createdAt:new Date().toISOString(),kind,text:note,resolved:false},...items].slice(0,100))} onToggle={id=>setFeedbackNotes(items=>items.map(note=>note.id===id?{...note,resolved:!note.resolved}:note))} onRemove={id=>setFeedbackNotes(items=>items.filter(note=>note.id!==id))}/></div></header>
 {view==="today"?<HomeView xp={xp} completed={completed} savedPhrases={savedPhrases} phraseReviews={phraseReviews} speakingAttempts={speakingAttempts} practiceDates={practiceDates} reviews={reviews} listeningPatterns={listeningPatterns} syncState={syncState} reviewNotice={reviewNotice} onClearNotice={()=>setReviewNotice("")} onRatePhrase={(phrase,rating)=>{schedulePhrase(phrase,rating);const remaining=savedPhrases.filter(item=>item!==phrase&&(!phraseReviews[item]||new Date(phraseReviews[item])<=new Date())).length;setReviewNotice(remaining?`Phrase reviewed · ${remaining} ${remaining===1?"item":"items"} still due.`:"Daily phrase review complete. Bien joué !")}} onExport={exportProgress} onPractice={(id,fromReview=false)=>{setReviewOrigin(fromReview);setReviewNotice("");setPassageId(id);setStep(0);setDone(false);setAssessment(null);setText("");setDiagnosis([]);setView("practice")}} onNavigate={target=>{if(target==="progress"){document.querySelector(".home-lower")?.scrollIntoView({behavior:"smooth"});return}setView(target)}}/>:view==="practice"?<div className="workspace"><aside className="session-rail"><p className="eyebrow">Today’s session</p><h2>{passage.title}</h2><div className="meta"><span>{passage.level}</span><span>{passage.topic}</span></div><ol className="steps">{labels.map((l,i)=><li key={l.name} className={i===step?"current":i<step?"complete":""}><span className="step-icon">{i<step?"✓":i+1}</span><div><strong>{l.name}</strong><small>{l.sub}</small></div></li>)}</ol><div className="session-stats"><div><strong>{completed.length}/{passages.length}</strong><span>lessons</span></div><div><strong>{duration?formatTime(duration):"–:––"}</strong><span>clip</span></div><div><strong>{step+1}/4</strong><span>steps</span></div></div></aside>
 <section className="practice" id="practice">{done?<div className="completion" id="progress"><div className="completion-mark">✓</div><p className="stage-label">{reviewOrigin?"Review complete":"Session complete"}</p><h1>Bien joué, Nikki.</h1><p className="intro">{reviewOrigin?"You completed this review. Choose when it should return, then head back to Today.":"How available did this French feel today? Your answer sets the next review."}</p><div className="score-grid"><div><strong>+{passage.xp}</strong><span>XP earned</span></div><div><strong>{savedPhrases.length}</strong><span>phrases saved</span></div><div><strong>{completed.length}/{passages.length}</strong><span>lessons completed</span></div></div><ReviewRating value={reviewRatings[passage.id]} onRate={rating=>scheduleReview(passage.id,rating)}/><button className="primary restart" onClick={()=>{if(reviewOrigin){setReviewOrigin(false);setReviewNotice(`Review complete · “${passage.title}” is scheduled to return.`);setView("today");return}setDone(false);setStep(0);setProgress(0);setDiagnosis([])}}>{reviewOrigin?"Return to Today":"Return to practice"} <span>→</span></button></div>:<>
 <div className="stage-label"><span>0{step+1}</span> {labels[step].name}</div>
 <h1>{["What did you catch?","Let’s close the gaps.",`Find ${passage.speaker.name}’s rhythm.`,"Now make it yours."][step]}</h1>
 <p className="intro">{["Listen at full speed. Don’t worry about every word—focus on the situation and the speaker’s main point.","Compare what you heard with the real phrasing. Mark why anything slipped past your ear.",`Speak along with ${passage.speaker.name}. Aim for the timing and melody—not a perfect accent.`,"Retell the situation naturally in French, without copying the transcript."][step]}</p>
 {step===0&&<div className="cefr-library" id="library"><div className="library-title"><div><span className="eyebrow">CEFR pathway</span><strong>Choose the right stretch</strong></div><small>{completed.length}/{passages.length} complete · {dueCount} due for review</small></div><div className="passage-row">{passages.map(p=><button key={p.id} className={p.id===passageId?"passage active":"passage"} onClick={()=>{clearAudio();setProgress(0);setAssessment(null);setText("");setPassageId(p.id)}}><span>{completed.includes(p.id)?"✓ ":""}{p.level}</span><strong>{p.title}</strong><small>{reviews[p.id]&&new Date(reviews[p.id])<=new Date()?"Review due":`${p.topic} · +${p.xp} XP`}</small></button>)}</div>{savedPhrases.length>0&&<div className="saved-strip"><strong>Saved phrases</strong>{savedPhrases.map(phrase=><button key={phrase} onClick={()=>setSavedPhrases(items=>items.filter(item=>item!==phrase))}>{phrase}<span>×</span></button>)}</div>}</div>}
 {step===0&&<Player passage={passage} playing={playing} onToggle={toggleSample} onReplay={replaySample} progress={progress} duration={duration}/>}
 {voiceError&&<p className="ai-error" role="alert">{voiceError}</p>}
 {step===0&&<><div className="no-transcript standalone"><span>◉</span> Transcript hidden for your first listen</div><Response label="Summarize what you understood" hint="English or French is fine" text={text} setText={value=>{setText(value);setAssessment(null)}} placeholder="I think they’re talking about…"/>{assessing&&<div className="ai-loading">Checking the ideas you caught…</div>}{assessmentError&&<p className="ai-error" role="alert">{assessmentError}</p>}{assessment&&<div className="comprehension-result"><div><strong>{assessment.score}%</strong><span>first-listen comprehension</span></div><section><h3>You caught</h3><ul>{assessment.understood.map(item=><li key={item}>{item}</li>)}</ul>{assessment.missed.length>0&&<><h3>Listen for next</h3><ul>{assessment.missed.map(item=><li key={item}>{item}</li>)}</ul></>}<p><b>Second-listen target:</b> {assessment.listening_target}</p></section></div>}</>}
 {step>0&&<Player passage={passage} playing={playing} onToggle={toggleSample} onReplay={replaySample} progress={progress} duration={duration}/>}
 {step===1&&<div className="decode-card"><p><button className="line-play" onClick={toggleSample} aria-label={playing?"Pause passage":"Play passage"}>{playing?"Ⅱ":"▶"}</button> « {passage.decode} »</p><div className="translation">{passage.translation}</div><details className="full-transcript"><summary>Reveal full transcript</summary>{passage.text.split(/(?<=[.!?])\s+/).map((sentence,index)=><p key={sentence}><span>{String(index+1).padStart(2,"0")}</span>{sentence}</p>)}</details><div className="diagnosis"><span>What made this difficult?</span>{["New expression","Speech too fast","Sounded different","I understood it"].map(x=><button key={x} aria-pressed={diagnosis.includes(x)} className={diagnosis.includes(x)?"selected":""} onClick={()=>setDiagnosis(items=>items.includes(x)?items.filter(item=>item!==x):[...items,x])}>{x}</button>)}</div><div className="phrase-note"><strong>{passage.phrase}</strong><span>{passage.meaning}</span><button aria-pressed={savedPhrases.includes(passage.phrase)} className={savedPhrases.includes(passage.phrase)?"saved":""} onClick={toggleSavedPhrase}>{savedPhrases.includes(passage.phrase)?"✓ Saved":"＋ Save phrase"}</button></div></div>}
 {step===2&&<div className="shadow-card"><div className="shadow-row"><span>Original</span><div className="mini-wave">{waves.slice(0,20).map((h,i)=><i key={i} style={{height:h/2}}/>)}</div></div><div className="shadow-reference"><span className="eyebrow">French reference · follow along</span>{passage.text.split(/(?<=[.!?])\s+/).map((sentence,index)=><p key={sentence}><i>{String(index+1).padStart(2,"0")}</i>{sentence}</p>)}</div><div className="shadow-row"><span>Your turn</span><div className="empty-wave">Record up to 60 seconds. Coaching checks words, rhythm, pauses, and likely liaison practice points without pretending to score individual sounds.</div></div><VoiceRecorder label="Start shadowing" recording={recording} setRecording={setRecording} onAttempt={rememberSpeaking} referenceText={passage.text}/></div>}
 {step===3&&<Response label="Retell the story in French" hint="Write it or record 30–60 seconds" text={text} setText={setText} placeholder={`${passage.speaker.name} raconte que…`} allowVoice onAttempt={rememberSpeaking}/>}
 <div className="bottom-actions"><button className="secondary" onClick={()=>step>0?setStep(step-1):setStep(1)}>{step?"← Back":"Skip assessment"}</button><button className="primary" disabled={assessing||(step===0&&!text.trim())} onClick={handlePrimary}>{step===0?(assessment?"Continue to decode":"Check my understanding"):["","Continue to shadowing","Continue to retell","Finish session"][step]} <span>→</span></button></div></>}
 </section></div>:view==="library"?<LibraryView completed={completed} savedPhrases={savedPhrases} reviews={reviews} onChoose={id=>{setPassageId(id);setStep(0);setDone(false);setAssessment(null);setText("");setDiagnosis([]);setView("practice")}} onRemovePhrase={phrase=>setSavedPhrases(items=>items.filter(item=>item!==phrase))}/>:view==="studio"?<StudioView youtubeUrl={youtubeUrl} setYoutubeUrl={setYoutubeUrl} videoId={videoId} setVideoId={setVideoId} clipStart={clipStart} setClipStart={setClipStart} clipEnd={clipEnd} setClipEnd={setClipEnd} urlError={urlError} setUrlError={setUrlError} loadVideo={loadVideo} onAttempt={rememberSpeaking}/>:<AboutView completed={completed.length} saved={savedPhrases.length} speaking={speakingAttempts.length} patterns={listeningPatterns}/>}</main>
}

export default function Page(){return <AccessGate><Home/></AccessGate>}

function HomeView({xp,completed,savedPhrases,phraseReviews,speakingAttempts,practiceDates,reviews,listeningPatterns,syncState,reviewNotice,onClearNotice,onRatePhrase,onExport,onPractice,onNavigate}:{xp:number;completed:string[];savedPhrases:string[];phraseReviews:Record<string,string>;speakingAttempts:SpeakingAttempt[];practiceDates:string[];reviews:Record<string,string>;listeningPatterns:Record<string,number>;syncState:"local"|"syncing"|"synced";reviewNotice:string;onClearNotice:()=>void;onRatePhrase:(phrase:string,rating:"Again"|"Hard"|"Good"|"Easy")=>void;onExport:()=>void;onPractice:(id:string,fromReview?:boolean)=>void;onNavigate:(view:"today"|"practice"|"library"|"studio"|"progress")=>void}){
 const now=new Date();
 const savedCount=savedPhrases.length;
 const duePhrases=savedPhrases.filter(phrase=>!phraseReviews[phrase]||new Date(phraseReviews[phrase])<=now);
 const due=passages.filter(p=>reviews[p.id]&&new Date(reviews[p.id])<=now);
 const patterns=Object.entries(listeningPatterns).sort((a,b)=>b[1]-a[1]);
 const topPattern=patterns[0]?.[0];
 const nextLesson=topPattern==="Speech too fast"?passages.find(p=>p.id==="train"):topPattern==="Sounded different"?passages.find(p=>p.id==="pluie"):passages.find(p=>!completed.includes(p.id))||passages[0];
 const primary=due[0]||nextLesson;
 const week=Array.from({length:7},(_,index)=>{const date=new Date();date.setDate(date.getDate()-(6-index));const key=date.toISOString().slice(0,10);return {key,label:date.toLocaleDateString("en-US",{weekday:"short"}).slice(0,1),active:practiceDates.includes(key),today:index===6}});
 const nextReview=Object.values(reviews).filter(date=>new Date(date)>now).sort()[0];
 return <section className="home-view" aria-labelledby="home-title">
  {reviewNotice&&<div className="review-confirmation" role="status"><span>✓</span><strong>{reviewNotice}</strong><button onClick={onClearNotice} aria-label="Dismiss review confirmation">×</button></div>}
  <div className="home-intro">
   <div><p className="eyebrow">Today’s listening brief</p><h1 id="home-title">Bonjour, Nikki.</h1><p>Small, attentive sessions are turning real French into something your ear can hold.</p></div>
   <div className="sync-tools"><span className={`sync-state ${syncState}`}>{syncState==="synced"?"✓ Progress synced":syncState==="syncing"?"Syncing…":"Saved on this device"}</span><button onClick={onExport}>Export backup</button></div>
  </div>
  <div className="home-grid">
   <article className="daily-note"><div className="note-top"><span>{due.length?"Review is ready":"Today’s recommendation"}</span><small>{primary.level} · {primary.topic}</small></div><div className="note-copy"><p>{due.length?"Before you learn anything new":"A good next stretch"}</p><h2>{primary.title}</h2><p>{due.length?"Listen once without reading. Notice what now feels obvious, then rate how easily it came back.":topPattern?`Chosen to work on “${topPattern.toLowerCase()},” the listening obstacle you’ve marked most often.`:"Start with one everyday story and let the four-step routine do the work."}</p></div><button onClick={()=>onPractice(primary.id,due.length>0)}>{due.length?"Review this passage":"Start today’s lesson"} <span>→</span></button><div className="note-stamp">à<br/>l’oreille</div></article>
   <div className="home-side"><article className="week-card"><div><p className="eyebrow">Your week</p><strong>{practiceDates.length} listening {practiceDates.length===1?"day":"days"} so far</strong></div><div className="week-dots">{week.map(day=><div key={day.key} className={day.active?"active":day.today?"today":""}><i>{day.active?"✓":""}</i><span>{day.label}</span></div>)}</div><p>Consistency matters more than keeping a perfect streak.</p></article><article className="home-stats"><div><strong>{completed.length}<span>/{passages.length}</span></strong><small>lessons complete</small></div><div><strong>{savedCount}</strong><small>phrases kept</small></div><div><strong>{xp}</strong><small>total XP</small></div></article></div>
  </div>
  <PhraseReviewDeck phrases={duePhrases} onRate={onRatePhrase}/>
  <div className="home-lower">
   <article className="insight-card"><div><p className="eyebrow">Listening insight</p><h2>{topPattern||"Your earprint starts here"}</h2><p>{topPattern?"This keeps appearing in your Decode notes. The app will favor passages that help you hear it more clearly.":"Mark what made a passage difficult during Decode, and this space will reveal useful patterns over time."}</p></div><div className="mini-patterns">{patterns.length?patterns.slice(0,3).map(([label,count])=><div key={label}><span>{label}</span><i><b style={{width:`${Math.max(20,count/(patterns[0][1]||1)*100)}%`}}/></i></div>):<span className="no-pattern">Complete a lesson to unlock your first insight.</span>}</div><button onClick={()=>onNavigate("library")}>Find a matching lesson →</button></article>
   <DailyReviewCard dueLessons={due} duePhrases={duePhrases} nextReview={nextReview} onReviewLesson={id=>onPractice(id,true)} onReviewPhrases={()=>document.getElementById("phrase-review")?.scrollIntoView({behavior:"smooth",block:"center"})}/>
   <article className="studio-card"><span className="studio-orbit">écoute</span><div><p className="eyebrow">Listening studio</p><h2>Bring something she already loves.</h2><p>Turn a recipe, interview, or travel video into a focused one-minute French drill.</p><button onClick={()=>onNavigate("studio")}>Open Studio →</button></div></article>
  </div>
  <SpeakingHistory attempts={speakingAttempts}/>
 </section>
}

function DailyReviewCard({dueLessons,duePhrases,nextReview,onReviewLesson,onReviewPhrases}:{dueLessons:Passage[];duePhrases:string[];nextReview?:string;onReviewLesson:(id:string)=>void;onReviewPhrases:()=>void}){
 const total=dueLessons.length+duePhrases.length;
 const firstLesson=dueLessons[0];
 return <article className={`queue-card interactive ${total?"has-items":"complete"}`}><div className="queue-heading"><div><p className="eyebrow">Daily review</p><h2>{total?"Your review path":"All caught up"}</h2></div><strong>{total?total:"✓"}<small>{total?total===1?"item":"items":"done"}</small></strong></div>{total?<><p>Complete each step and it will be scheduled for its next appearance.</p><ol className="review-path"><li className={duePhrases.length?"ready":"done"}><span>{duePhrases.length?"1":"✓"}</span><div><strong>Saved phrases</strong><small>{duePhrases.length?`${duePhrases.length} ready for recall`:"Complete"}</small></div>{duePhrases.length>0&&<button onClick={onReviewPhrases}>Review phrases →</button>}</li><li className={firstLesson?"ready":"done"}><span>{firstLesson?duePhrases.length?"2":"1":"✓"}</span><div><strong>Listening passage</strong><small>{firstLesson?firstLesson.title:"Complete"}</small></div>{firstLesson&&<button onClick={()=>onReviewLesson(firstLesson.id)}>Open passage →</button>}</li></ol></>:<><p>Your review is complete. New items will appear here when they are ready.</p><div className="queue-complete-mark">✓ Review complete</div>{nextReview&&<small className="next-review-date">Next review · {new Date(nextReview).toLocaleDateString("en-US",{month:"short",day:"numeric"})}</small>}</>}</article>
}

function PhraseReviewDeck({phrases,onRate}:{phrases:string[];onRate:(phrase:string,rating:"Again"|"Hard"|"Good"|"Easy")=>void}){
 const [index,setIndex]=useState(0),[revealed,setRevealed]=useState(false);
 const phrase=phrases[index%Math.max(phrases.length,1)];
 if(!phrase)return <section className="phrase-review empty" id="phrase-review"><div><p className="eyebrow">Phrase review</p><h2>Your phrase queue is clear.</h2><p>Highlight French in a lesson or the Library to build a personal review deck.</p></div></section>;
 const source=passages.find(p=>p.phrase===phrase||p.text.includes(phrase));
 const rate=(rating:"Again"|"Hard"|"Good"|"Easy")=>{onRate(phrase,rating);setRevealed(false);setIndex(value=>value+1)};
 const play=async()=>{const blob=await loadSpeech(phrase,undefined,source?.speaker.voice);const url=URL.createObjectURL(blob);const audio=new Audio(url);audio.onended=()=>URL.revokeObjectURL(url);await audio.play()};
 return <section className="phrase-review" id="phrase-review"><div className="phrase-review-head"><div><p className="eyebrow">Phrase review · {phrases.length} due</p><h2>Recall it before you reveal it.</h2></div><button onClick={()=>void play()} aria-label="Play saved phrase">▶ Hear it</button></div><blockquote>{phrase}</blockquote>{revealed?<><p className="phrase-context">{source?.phrase===phrase?source.meaning:source?`From “${source.title}”`:"Your highlighted French"}</p><ReviewRating onRate={rate}/></>:<button className="reveal-phrase" onClick={()=>setRevealed(true)}>Reveal context</button>}</section>
}

function SpeakingHistory({attempts}:{attempts:SpeakingAttempt[]}){
 return <section className="speaking-history"><div><p className="eyebrow">Speaking history</p><h2>{attempts.length?"Your voice, getting freer.":"Your speaking attempts will collect here."}</h2><p>{attempts.length?"Compare the transcript and next drill from recent shadowing and retelling attempts.":"Record during Shadow or Retell to keep the transcript, coaching, and next drill."}</p></div>{attempts.length>0&&<div className="attempt-list">{attempts.slice(0,5).map(attempt=><article key={attempt.id}><div><span>{new Date(attempt.createdAt).toLocaleDateString("en-US",{month:"short",day:"numeric"})}</span><strong>{attempt.task}</strong><em>{attempt.level} · {attempt.score}/100</em></div><blockquote>{attempt.transcript}</blockquote><p>{attempt.summary}</p><small>Next drill · {attempt.nextDrill}</small></article>)}</div>}</section>
}

function LibraryView({completed,savedPhrases,reviews,onChoose,onRemovePhrase}:{completed:string[];savedPhrases:string[];reviews:Record<string,string>;onChoose:(id:string)=>void;onRemovePhrase:(phrase:string)=>void}){
 return <section className="standalone-view" aria-labelledby="library-title"><p className="eyebrow">Lesson library</p><h1 id="library-title">Choose what your ear needs next.</h1><p className="intro">Move from everyday B1 conversation toward the nuance and pace of B2 French. Highlight any French in a passage to save exactly what matters.</p><div className="library-grid">{passages.map(p=>{const due=reviews[p.id]&&new Date(reviews[p.id])<=new Date();return <article key={p.id} className={completed.includes(p.id)?"complete":""}><div><span>{p.level}</span><em>{p.topic}</em></div><h2>{p.title}</h2><p>{p.text}</p><footer><small>{due?"Review due now":completed.includes(p.id)?"Completed":"New lesson"}</small><button onClick={()=>onChoose(p.id)}>{due?"Review lesson":completed.includes(p.id)?"Practice again":"Start lesson"} →</button></footer></article>})}</div><div className="phrase-library"><div><p className="eyebrow">Phrase notebook</p><h2>{savedPhrases.length?savedPhrases.length+" phrases worth keeping":"Your saved phrases will live here."}</h2></div>{savedPhrases.length?<div>{savedPhrases.map(phrase=>{const source=passages.find(p=>p.phrase===phrase||p.text.includes(phrase)||p.title.includes(phrase));return <article key={phrase}><strong>{phrase}</strong><span>{source?.phrase===phrase?source.meaning:source?`From ${source.title}`:"Saved from lesson text"}</span><button onClick={()=>onRemovePhrase(phrase)} aria-label={`Remove ${phrase}`}>×</button></article>})}</div>:<p>Highlight any French phrase or sentence, then choose “Save phrase.” It will appear here for review.</p>}</div></section>
}

function ReviewRating({value,onRate}:{value?:string;onRate:(rating:"Again"|"Hard"|"Good"|"Easy")=>void}){
 const choices=[["Again","Today"],["Hard","Tomorrow"],["Good","3 days"],["Easy","1 week"]] as const;
 return <div className="review-rating" aria-label="Choose the next review interval"><span>When should this return?</span><div>{choices.map(([rating,interval])=><button key={rating} className={value===rating?"selected":""} aria-pressed={value===rating} onClick={()=>onRate(rating)}><strong>{rating}</strong><small>{interval}</small></button>)}</div></div>
}

function AboutView({completed,saved,speaking,patterns}:{completed:number;saved:number;speaking:number;patterns:Record<string,number>}){
 const stage=completed===0?0:completed<4?1:completed<9?2:3;
 const topPattern=Object.entries(patterns).sort((a,b)=>b[1]-a[1])[0]?.[0];
 const guidance=[
  {label:"Your first week",title:"Begin by trusting your ear.",copy:"Nikki, this app was made for where you are now: you know more French than fast conversation lets you access. Start with short B1 stories. On the first listen, understanding the situation is enough."},
  {label:"Building recognition",title:"You are teaching sound to become meaning.",copy:"The goal is not to memorize every transcript. It is to notice phrases at natural speed, understand why they slipped past, and meet them again before they fade."},
  {label:"Growing independence",title:"Your listening is becoming active.",copy:"You are ready to mix structured passages with Studio clips. Keep captions hidden at first, then use the transcript as evidence—not as a substitute for listening."},
  {label:"Toward B2",title:"Now variety matters.",copy:"Your ear benefits from different speakers, topics, speeds, and opinions. Retelling and shadowing will help turn comprehension into French you can use spontaneously."},
 ][stage];
 return <section className="about-view" aria-labelledby="about-title"><div className="about-letter"><p className="eyebrow">Why À l’Oreille exists</p><h1 id="about-title">French that reaches you before the subtitles do.</h1><p className="about-lede">This is not a vocabulary game or a race for a streak. It is a listening coach created for you, Nikki, while you grow from understanding written French into following the living, everyday language people actually speak.</p><div className="letter-signoff"><span>Made with care for your French journey</span><strong>à l’oreille</strong></div></div><div className="about-now"><div><span>{String(stage+1).padStart(2,"0")}</span><p className="eyebrow">{guidance.label}</p><h2>{guidance.title}</h2><p>{guidance.copy}</p>{topPattern&&<p className="personal-note"><b>Your current listening focus:</b> {topPattern.toLowerCase()}.</p>}</div><div className="about-tally"><div><strong>{completed}</strong><span>lessons heard</span></div><div><strong>{saved}</strong><span>phrases kept</span></div><div><strong>{speaking}</strong><span>times you spoke</span></div></div></div><div className="loop-explainer"><p className="eyebrow">The learning loop</p><h2>Every source becomes four useful encounters.</h2><div>{labels.map((item,index)=><article key={item.name}><span>0{index+1}</span><h3>{item.name}</h3><p>{["Listen without reading and catch the situation before the details.","Reveal the words, diagnose the gap, and save language worth keeping.","Copy the timing and melody so fast French feels less compressed.","Explain the idea in your own French so recognition becomes expression."][index]}</p></article>)}</div></div><div className="about-principles"><article><h2>You do not need every word.</h2><p>Real listening is prediction, context, repair, and confidence. Missing a word is information—not failure.</p></article><article><h2>Your data serves the next lesson.</h2><p>Saved phrases, difficult sounds, reviews, and speaking attempts quietly shape what the app recommends next.</p></article><article><h2>The app will grow with you.</h2><p>This page and your daily practice guidance change as your listening history shows that you are ready for more speed, nuance, and independence.</p></article></div></section>
}

function StudioView({youtubeUrl,setYoutubeUrl,videoId,setVideoId,clipStart,setClipStart,clipEnd,setClipEnd,urlError,setUrlError,loadVideo,onAttempt}:{youtubeUrl:string;setYoutubeUrl:(value:string)=>void;videoId:string|null;setVideoId:(value:string|null)=>void;clipStart:number;setClipStart:(value:number)=>void;clipEnd:number;setClipEnd:(value:number)=>void;urlError:string;setUrlError:(value:string)=>void;loadVideo:()=>void;onAttempt:(attempt:SpeakingAttempt)=>void}){
 const [studioStep,setStudioStep]=useState(0),[transcript,setTranscript]=useState(""),[cues,setCues]=useState<CaptionCue[]>([]),[videoDuration,setVideoDuration]=useState(0),[captionSource,setCaptionSource]=useState<"manual"|"automatic"|null>(null),[captionReason,setCaptionReason]=useState(""),[transcriptState,setTranscriptState]=useState<"idle"|"loading"|"found"|"missing">("idle"),[summary,setSummary]=useState(""),[feedback,setFeedback]=useState<ComprehensionFeedback|null>(null),[checking,setChecking]=useState(false),[studioError,setStudioError]=useState(""),[recording,setRecording]=useState(false);
 const clipTranscript=cues.length?cues.filter(cue=>cue.start<clipEnd&&cue.start+Math.max(cue.duration,.5)>clipStart).map(cue=>cue.text).filter((text,index,all)=>text!==all[index-1]).join(" ").replace(/\s+([,.!?;:])/g,"$1").trim():transcript;
 useEffect(()=>{if(!videoId)return;setStudioStep(0);setSummary("");setFeedback(null);setTranscript("");setCues([]);setCaptionSource(null);setCaptionReason("");setTranscriptState("loading");fetch("/api/youtube-transcript",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({videoId})}).then(response=>response.json()).then(data=>{const nextDuration=Number(data.durationSeconds)||0;if(nextDuration){setVideoDuration(nextDuration);setClipStart(0);setClipEnd(Math.min(60,nextDuration))}if(data.transcript){setTranscript(data.transcript);setCues(Array.isArray(data.cues)?data.cues:[]);setCaptionSource(data.source||null);setTranscriptState("found")}else{setCaptionReason(data.reason||"French captions could not be retrieved.");setTranscriptState("missing")}}).catch(()=>{setCaptionReason("French captions could not be retrieved.");setTranscriptState("missing")})},[videoId,setClipEnd,setClipStart]);
 const check=async()=>{if(!clipTranscript.trim()){setStudioError("Add a transcript before checking comprehension.");return}setChecking(true);setStudioError("");try{const response=await fetch("/api/comprehension",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({summary,passage:clipTranscript.slice(0,6000),level:"B1-B2"})});const data=await response.json();if(!response.ok)throw new Error(data.error);setFeedback(data)}catch(error){setStudioError(error instanceof Error?error.message:"Feedback is unavailable.")}finally{setChecking(false)}};
 const resetVideo=()=>{setVideoId(null);setYoutubeUrl("");setStudioStep(0);setTranscript("");setSummary("");setFeedback(null)};
 return <section className="standalone-view studio-view" aria-labelledby="studio-title">
  <p className="eyebrow">Listening studio</p><h1 id="studio-title">Bring your own French.</h1>
  <p className="intro">Use the same learning loop with interviews, recipes, travel videos, or anything you already enjoy.</p>
  {!videoId?<div className="studio-workbench"><div className="studio-controls"><div className="studio-number">01</div><h2>Choose a short clip</h2><div className="url-row"><span className="youtube-badge">▶</span><input type="url" value={youtubeUrl} onChange={e=>{setYoutubeUrl(e.target.value);setUrlError("")}} onKeyDown={e=>e.key==="Enter"&&loadVideo()} placeholder="https://www.youtube.com/watch?v=…" aria-label="YouTube URL"/><button onClick={loadVideo}>Build practice loop</button></div>{urlError&&<p className="url-error" role="alert">{urlError}</p>}<p className="import-help">Public videos with French captions work best. If captions cannot be retrieved, you can paste the transcript.</p><div className="studio-method">{labels.map((item,index)=><div key={item.name}><span>{index+1}</span><p><strong>{item.name}</strong>{item.sub}</p></div>)}</div></div><div className="studio-screen"><div className="studio-empty"><span>écoute</span><strong>Your clip becomes a lesson</strong><p>One source. Four deliberate passes. No passive scrolling.</p></div></div></div>:
  <div className="studio-loop"><aside><button className="change-video" onClick={resetVideo}>← Choose another video</button><p className="eyebrow">Studio session</p><ol className="steps">{labels.map((item,index)=><li key={item.name} className={index===studioStep?"current":index<studioStep?"complete":""}><span className="step-icon">{index<studioStep?"✓":index+1}</span><div><strong>{item.name}</strong><small>{item.sub}</small></div></li>)}</ol></aside>
   <div className="studio-lesson"><ClipTimeline duration={videoDuration} start={clipStart} end={clipEnd} onStart={value=>{setClipStart(value);setFeedback(null)}} onEnd={value=>{setClipEnd(value);setFeedback(null)}}/><div className="stage-label"><span>0{studioStep+1}</span> {labels[studioStep].name}</div><h2>{["What did you catch?","Close the gaps.","Find the speaker’s rhythm.","Now make it yours."][studioStep]}</h2><YouTubePlayer videoId={videoId} start={clipStart} end={clipEnd}/>
   {studioStep===0&&<><div className={`caption-status ${transcriptState}`}>{transcriptState==="loading"?"Reading the video’s French captions…":transcriptState==="found"?`✓ ${captionSource==="automatic"?"Automatic":"Creator-provided"} French captions found · transcript built for ${formatTime(clipStart)}–${formatTime(clipEnd)}`:`${captionReason} Paste French text below to continue.`}</div>{transcriptState==="missing"&&<textarea className="transcript-input" value={transcript} onChange={e=>setTranscript(e.target.value)} placeholder="Paste the French transcript here…"/>}<Response label="Summarize what you understood" hint="English or French is fine" text={summary} setText={value=>{setSummary(value);setFeedback(null)}} placeholder="The speaker is explaining…"/>{feedback&&<div className="comprehension-result"><div><strong>{feedback.score}%</strong><span>first-listen comprehension</span></div><section><h3>You caught</h3><ul>{feedback.understood.map(item=><li key={item}>{item}</li>)}</ul><h3>Listen for next</h3><ul>{feedback.missed.map(item=><li key={item}>{item}</li>)}</ul><p><b>Second-listen target:</b> {feedback.listening_target}</p></section></div>}</>}
   {studioStep===1&&<div className="studio-transcript"><p className="selection-hint">Transcript for this selected passage · highlight any French to save it.</p>{clipTranscript?<p>{clipTranscript}</p>:<><p>Paste a transcript to decode this clip and save phrases from it.</p><textarea value={transcript} onChange={e=>setTranscript(e.target.value)} placeholder="Paste the French transcript here…"/></>}</div>}
   {studioStep===2&&<div className="shadow-card"><div className="shadow-row"><span>Original</span><p>Replay one sentence, then speak over it until the timing feels natural.</p></div><div className="shadow-reference"><span className="eyebrow">French reference · follow along</span>{clipTranscript.split(/(?<=[.!?])\s+/).filter(Boolean).map((sentence,index)=><p key={`${index}-${sentence}`}><i>{String(index+1).padStart(2,"0")}</i>{sentence}</p>)}</div><VoiceRecorder label="Start Studio shadowing" recording={recording} setRecording={setRecording} onAttempt={onAttempt} referenceText={clipTranscript}/></div>}
   {studioStep===3&&<Response label="Retell the clip in French" hint="Use your own words" text={summary} setText={setSummary} placeholder="Dans cette vidéo…" allowVoice onAttempt={onAttempt}/>}
   {studioError&&<p className="ai-error" role="alert">{studioError}</p>}<div className="bottom-actions"><button className="secondary" disabled={studioStep===0} onClick={()=>setStudioStep(value=>Math.max(0,value-1))}>← Back</button><button className="primary" disabled={checking||(studioStep===0&&!summary.trim())} onClick={()=>{if(studioStep===0&&!feedback){void check();return}setStudioStep(value=>Math.min(3,value+1))}}>{checking?"Checking…":studioStep===0&&!feedback?"Check understanding":studioStep===3?"Practice again":"Continue"} <span>→</span></button></div>
   </div>
  </div>}
 </section>
}

function ProgressView({xp,completed,savedCount,practiceDates,reviews,reviewRatings,listeningPatterns,onRate,onReview}:{xp:number;completed:string[];savedCount:number;practiceDates:string[];reviews:Record<string,string>;reviewRatings:Record<string,string>;listeningPatterns:Record<string,number>;onRate:(id:string,rating:"Again"|"Hard"|"Good"|"Easy")=>void;onReview:(id:string)=>void}){
 const due=passages.filter(p=>reviews[p.id]&&new Date(reviews[p.id])<=new Date());
 const next=passages.filter(p=>reviews[p.id]&&new Date(reviews[p.id])>new Date()).sort((a,b)=>reviews[a.id].localeCompare(reviews[b.id]));
 const patterns=Object.entries(listeningPatterns).sort((a,b)=>b[1]-a[1]);
 const topPattern=patterns[0]?.[0];
 const recommendation=topPattern==="New expression"?passages.find(p=>!completed.includes(p.id)&&p.topic==="Conversation"):topPattern==="Speech too fast"?passages.find(p=>p.id==="train"):topPattern==="Sounded different"?passages.find(p=>p.id==="pluie"):passages.find(p=>!completed.includes(p.id));
 return <section className="standalone-view progress-view" aria-labelledby="progress-title"><p className="eyebrow">Your progress</p><h1 id="progress-title">A clearer ear, one session at a time.</h1><div className="progress-cards"><article><strong>{xp}</strong><span>Total XP</span></article><article><strong>{completed.length}/{passages.length}</strong><span>Lessons completed</span></article><article><strong>{practiceDates.length}</strong><span>Practice days</span></article><article><strong>{savedCount}</strong><span>Phrases saved</span></article></div><div className="review-panel"><div><p className="eyebrow">Today’s review</p><h2>{due.length?`${due.length} ${due.length===1?"lesson is":"lessons are"} ready`:"Your queue is clear"}</h2><p>{due.length?"Try each passage without the transcript, then tell the app how available it felt.":next.length?`Next review: ${new Date(reviews[next[0].id]).toLocaleDateString()}`:"Complete a lesson to begin your review schedule."}</p></div>{due.length>0&&<div>{due.map(p=><article className="review-item" key={p.id}><button className="review-open" onClick={()=>onReview(p.id)}><span>{p.level}</span><strong>{p.title}</strong><em>Open →</em></button><ReviewRating value={reviewRatings[p.id]} onRate={rating=>onRate(p.id,rating)}/></article>)}</div>}</div><div className="earprint"><div><p className="eyebrow">Your earprint</p><h2>{topPattern?topPattern:"Patterns appear as you practice"}</h2><p>{topPattern?"This is the obstacle you’ve marked most often. The recommendation beside it targets that exact kind of listening.":"During Decode, mark what made a passage difficult. We’ll turn those answers into a useful pattern—not a generic score."}</p></div><div className="pattern-bars">{patterns.length?patterns.map(([label,count])=><div key={label}><span>{label}</span><i><b style={{width:`${Math.max(18,count/(patterns[0][1]||1)*100)}%`}}/></i><strong>{count}</strong></div>):<div className="earprint-empty">No weak spots recorded yet.</div>}</div>{recommendation&&<button className="recommendation" onClick={()=>onReview(recommendation.id)}><span>Recommended next</span><strong>{recommendation.title}</strong><small>{recommendation.level} · {recommendation.topic} →</small></button>}</div><div className="level-track"><span style={{width:`${Math.min(100,completed.length/passages.length*100)}%`}}/><div><b>B1 foundation</b><b>B2 independence</b></div></div></section>
}

function YouTubePlayer({videoId,start,end}:{videoId:string;start:number;end:number}){return <div className="youtube-player"><iframe src={`https://www.youtube-nocookie.com/embed/${videoId}?cc_load_policy=0&rel=0&start=${start}&end=${end}`} title="Imported YouTube clip for French listening practice" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/></div>}

function Response({label,hint,text,setText,placeholder,allowVoice=false,onAttempt}:{label:string;hint:string;text:string;setText:(v:string)=>void;placeholder:string;allowVoice?:boolean;onAttempt?:(attempt:SpeakingAttempt)=>void}){const [recording,setRecording]=useState(false);return <div className="response-block"><label><strong>{label}</strong><span>{hint}</span></label><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={placeholder} maxLength={500}/><div className="response-footer"><span>{text.length} / 500</span>{allowVoice&&<span className="voice-hint">or use the recorder below</span>}</div>{allowVoice&&<VoiceRecorder label="Record my retell" recording={recording} setRecording={setRecording} onAttempt={onAttempt}/>}</div>}

async function measureSpeechTiming(blob:Blob){
 const context=new AudioContext();
 try{const buffer=await context.decodeAudioData(await blob.arrayBuffer());const data=buffer.getChannelData(0),windowSize=Math.max(1,Math.floor(buffer.sampleRate*.05)),levels:number[]=[];for(let start=0;start<data.length;start+=windowSize){let sum=0,end=Math.min(data.length,start+windowSize);for(let i=start;i<end;i++)sum+=data[i]*data[i];levels.push(Math.sqrt(sum/Math.max(1,end-start)))}const peak=Math.max(...levels,.001),threshold=Math.max(.008,peak*.12);let silentRun=0,longest=0,pauses=0,silentWindows=0;for(const level of levels){if(level<threshold){silentRun++;silentWindows++}else{if(silentRun>=6)pauses++;longest=Math.max(longest,silentRun);silentRun=0}}if(silentRun>=6)pauses++;longest=Math.max(longest,silentRun);return{duration_seconds:Number(buffer.duration.toFixed(1)),pause_count:pauses,longest_pause_seconds:Number((longest*.05).toFixed(1)),speaking_ratio:Number((1-silentWindows/Math.max(1,levels.length)).toFixed(2))}}finally{void context.close()}
}

function VoiceRecorder({label,recording,setRecording,onAttempt,referenceText=""}:{label:string;recording:boolean;setRecording:(v:boolean)=>void;onAttempt?:(attempt:SpeakingAttempt)=>void;referenceText?:string}){
 const recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]),stopTimer=useRef<number|null>(null);const [audioUrl,setAudioUrl]=useState(""),[error,setError]=useState(""),[analyzing,setAnalyzing]=useState(false),[result,setResult]=useState<{transcript:string;feedback:{cefr_estimate:string;score:number;summary:string;strengths:string[];corrections:string[];word_accuracy:string;rhythm:string;pauses:string;liaison_practice:string;replay_drill:string;next_drill:string;xp_earned:number}}|null>(null);
 const analyze=async(blob:Blob)=>{setAnalyzing(true);setResult(null);try{const timing=await measureSpeechTiming(blob).catch(()=>null);const form=new FormData();form.append("audio",blob,"recording.webm");form.append("level","B1-B2");form.append("task",label.toLowerCase());if(referenceText)form.append("reference",referenceText);if(timing)form.append("timing",JSON.stringify(timing));const response=await fetch("/api/feedback",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||"AI feedback is unavailable.");setResult(data);onAttempt?.({id:crypto.randomUUID(),createdAt:new Date().toISOString(),task:label,transcript:data.transcript,score:data.feedback.score,level:data.feedback.cefr_estimate,summary:data.feedback.summary,nextDrill:data.feedback.replay_drill})}catch(e){setError(e instanceof Error?e.message:"AI feedback is unavailable.")}finally{setAnalyzing(false)}};
 const toggle=async()=>{if(recording){if(stopTimer.current)window.clearTimeout(stopTimer.current);recorder.current?.stop();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const next=new MediaRecorder(stream);recorder.current=next;next.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};next.onstop=()=>{if(stopTimer.current)window.clearTimeout(stopTimer.current);const blob=new Blob(chunks.current,{type:next.mimeType});setAudioUrl(URL.createObjectURL(blob));stream.getTracks().forEach(t=>t.stop());setRecording(false);void analyze(blob)};next.start();stopTimer.current=window.setTimeout(()=>next.state==="recording"&&next.stop(),60000);setError("");setRecording(true)}catch{setError("Microphone access is needed to record your voice.")}};
 return <div className="recorder"><button className={recording?"record active":"record"} onClick={toggle}>{recording?"■ Stop recording":`● ${label}`}</button>{recording&&<span className="record-limit">Stops automatically at 1:00</span>}{audioUrl&&<audio controls src={audioUrl} aria-label="Your recorded French"/>}{analyzing&&<div className="ai-loading">Checking words, rhythm, pauses, and liaison practice…</div>}{error&&<p className="record-error">{error}</p>}{result&&<div className="ai-feedback"><div className="feedback-score"><strong>{result.feedback.score}</strong><span>{result.feedback.cefr_estimate} estimate</span><em>+{result.feedback.xp_earned} XP</em></div><div><p>{result.feedback.summary}</p><strong>What worked</strong><ul>{result.feedback.strengths.map(item=><li key={item}>{item}</li>)}</ul><strong>Your transcript</strong><blockquote>{result.transcript}</blockquote><div className="speech-coach-grid"><article><span>Words</span><p>{result.feedback.word_accuracy}</p></article><article><span>Rhythm</span><p>{result.feedback.rhythm}</p></article><article><span>Pauses</span><p>{result.feedback.pauses}</p></article><article><span>Liaison to practise</span><p>{result.feedback.liaison_practice}</p></article></div><strong>Refine next</strong><ul>{result.feedback.corrections.map(item=><li key={item}>{item}</li>)}</ul><div className="replay-drill"><span>Replay drill</span>{result.feedback.replay_drill}</div><div className="next-drill">Next drill · {result.feedback.next_drill}</div></div></div>}</div>
}
