"use client";
import {useEffect,useRef,useState} from "react";
type Recording={id:string;source:string;task:string;transcript:string;createdAt:number;ready:number};
export function SaveRecording({audioUrl,language,source,task,transcript}:{audioUrl:string;language:string;source:string;task:string;transcript:string}){
 const id=useRef(crypto.randomUUID()),[state,setState]=useState(""),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
 const save=async()=>{if(busy||saved)return;setBusy(true);try{const blob=await(await fetch(audioUrl)).blob(),form=new FormData();form.append("audio",blob,"recording");form.append("id",id.current);form.append("source",source);form.append("task",task);form.append("transcript",transcript);form.append("consent","save");const response=await fetch(`/api/recordings?language=${language}`,{method:"POST",body:form});const data=await response.json();if(!response.ok)throw Error(data.error||"Could not save.");setSaved(true);setState("Saved. Open Library → Recording journal to compare or delete it.")}catch(e){setState(e instanceof Error?e.message:"Could not save.")}finally{setBusy(false)}};
 return <div className="practice-tools"><p>Optional: save this audio and transcript privately to your account for comparison across devices. Up to 20 recordings per language; keep them until you delete them. Saving is separate from sending a recording for AI coaching.</p><button disabled={busy||saved} onClick={()=>void save()}>{busy?"Saving…":saved?"Recording saved":"Save audio to my private journal"}</button>{state&&<p role="status">{state}</p>}</div>;
}
export default function RecordingJournal({language}:{language:string}){
 const [items,setItems]=useState<Recording[]>([]),[selected,setSelected]=useState<string[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[deleting,setDeleting]=useState("");
 const endpoint=`/api/recordings?language=${language}`;
 useEffect(()=>{let active=true;fetch(endpoint,{cache:"no-store"}).then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error);if(active)setItems(data.recordings)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[endpoint]);
 const remove=async(id:string)=>{if(!window.confirm("Permanently delete this saved audio and transcript?"))return;setDeleting(id);try{const r=await fetch(endpoint+"&id="+id,{method:"DELETE"});if(!r.ok)throw Error("Deletion failed. Please retry.");setItems(items=>items.filter(item=>item.id!==id));setSelected(ids=>ids.filter(value=>value!==id))}catch(e){setError(e instanceof Error?e.message:"Deletion failed.")}finally{setDeleting("")}};
 const chosen=items.filter(i=>selected.includes(i.id));
 return <section className="practice-tools"><p className="eyebrow">Private recording journal</p><h2>Hear your progress for yourself.</h2><p>Select two recordings of the same task or phrase. Compare ease, pauses, and how clearly you express your idea. This is your own listening comparison, not an automatic pronunciation or CEFR assessment.</p>{loading&&<p>Loading recordings…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!items.length&&!error&&<p>After recording a rehearsal or retell, choose “Save audio to my private journal.” Recordings are never added here automatically.</p>}<div className="library-grid">{chosen.map(item=><article key={item.id}><h3>{item.task}</h3><small>{new Date(item.createdAt).toLocaleString()}</small><p>{item.source}</p><audio controls preload="none" src={endpoint+"&id="+item.id} aria-label={`${item.task}, ${new Date(item.createdAt).toLocaleString()}`}/><details><summary>Recorded transcript</summary><p>{item.transcript}</p></details></article>)}</div>{chosen.length===2&&chosen[0].source!==chosen[1].source&&<p role="status">These recordings use different source material. Differences may reflect the task, not progress.</p>}<ul>{items.map(item=><li key={item.id}><label><input type="checkbox" checked={selected.includes(item.id)} disabled={!item.ready||(!selected.includes(item.id)&&selected.length>=2)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,item.id]:ids.filter(id=>id!==item.id))}/>{item.task} · {new Date(item.createdAt).toLocaleString()}{!item.ready?" · Upload incomplete; delete to release the slot":""}</label><button disabled={!!deleting} onClick={()=>void remove(item.id)}>{deleting===item.id?"Deleting…":"Delete saved recording"}</button></li>)}</ul></section>;
}
