"use client";
import {useEffect,useRef,useState,type RefObject} from "react";
import {captureActive,CAPTURE_PLAYBACK_EVENT,holdAppPlayback} from "../lib/audio-capture";
import type {AudioExcerpt} from "../lib/audio-excerpts";
export default function ReplayTools({text,audio,loadAudio,excerpts=[],onExcerpts}:{text:string;audio:RefObject<HTMLAudioElement|null>;loadAudio:(text:string)=>Promise<Blob>;excerpts?:AudioExcerpt[];onExcerpts?:(items:AudioExcerpt[])=>void}){
 const [label,setLabel]=useState("");
 const sentences=text.split(/(?<=[.!?…])\s+|\n+/u).filter(Boolean),[selected,setSelected]=useState(0),[reveal,setReveal]=useState(false),[a,setA]=useState<number|null>(null),[b,setB]=useState<number|null>(null),[loop,setLoop]=useState(false),[status,setStatus]=useState("");
 const player=useRef<HTMLAudioElement|null>(null),url=useRef(""),generation=useRef(0);
 const stop=()=>{generation.current++;player.current?.pause();player.current=null;if(url.current)URL.revokeObjectURL(url.current);url.current="";};
 useEffect(()=>{const pause=()=>{stop();setStatus("");};window.addEventListener(CAPTURE_PLAYBACK_EVENT,pause);return()=>{stop();window.removeEventListener(CAPTURE_PLAYBACK_EVENT,pause);};},[]);
 useEffect(()=>{const tick=()=>{if(loop&&a!==null&&b!==null&&audio.current&&audio.current.currentTime>=b)audio.current.currentTime=a;};const id=window.setInterval(tick,100);return()=>clearInterval(id);},[loop,a,b,audio]);
 const listen=async()=>{if(captureActive())return;const release=holdAppPlayback();release();stop();const attempt=generation.current;setStatus("Preparing phrase…");try{const blob=await loadAudio(sentences[selected]);if(attempt!==generation.current||captureActive())return;url.current=URL.createObjectURL(blob);player.current=new Audio(url.current);player.current.onended=()=>setStatus("");await player.current.play();setStatus("Listening to this phrase");}catch{if(attempt===generation.current)setStatus("Could not play this phrase. Please retry.");}};
 return <section className="practice-tools" aria-label="Focused replay tools"><h3>I couldn’t hear this part</h3><p>Replay the original recording, or isolate a phrase with AI narration.</p><div className="tool-row"><button onClick={()=>{if(audio.current)audio.current.currentTime=Math.max(0,audio.current.currentTime-5);}}>Back 5 seconds</button><button onClick={()=>{setA(audio.current?.currentTime??0);setB(null);setLoop(false);}}>Mark A</button><button disabled={a===null} onClick={()=>{const time=audio.current?.currentTime??0;if(a!==null&&time>a+.5)setB(time);else setStatus("Play at least half a second beyond A before marking B.");}}>Mark B</button><button disabled={a===null||b===null} aria-pressed={loop} onClick={()=>{setLoop(!loop);if(!loop&&audio.current&&a!==null)audio.current.currentTime=a;}}>{loop?"Stop loop":"Loop A–B"}</button></div><p>{a!==null?`A: ${a.toFixed(1)}s`:"A not set"} · {b!==null?`B: ${b.toFixed(1)}s`:"B not set"}</p>
 {onExcerpts&&<div><label>Name this original-audio excerpt<input value={label} maxLength={100} onChange={e=>setLabel(e.target.value)} placeholder="The words I missed"/></label><button disabled={a===null||b===null||!label.trim()||excerpts.length>=20} onClick={()=>{if(a!==null&&b!==null){onExcerpts([...excerpts,{id:crypto.randomUUID(),label:label.trim(),start:a,end:b}]);setLabel("");setStatus("Excerpt saved with this lesson.")}}}>Save A–B excerpt</button><ul>{excerpts.map(e=><li key={e.id}><button onClick={async()=>{if(captureActive())return;const original=audio.current;if(!original){setStatus("Load the lesson audio above first, then replay your excerpt.");return}stop();setA(e.start);setB(e.end);setLoop(true);original.currentTime=e.start;try{await original.play();setStatus("Looping the original recording. Use Stop loop or pause above to stop.")}catch{setStatus("Could not play. Try the main audio player first.")}}}>{e.label} · {e.start.toFixed(1)}–{e.end.toFixed(1)}s</button><button aria-label={`Remove excerpt ${e.label}`} onClick={()=>onExcerpts(excerpts.filter(item=>item.id!==e.id))}>Remove</button></li>)}</ul><small>Exact positions in this lesson’s original audio, not regenerated speech. Up to 20 excerpts per lesson.</small></div>}
 <label>Phrase <select value={selected} onChange={e=>{stop();setSelected(Number(e.target.value));setReveal(false);setStatus("");}}>{sentences.map((_,i)=><option key={i} value={i}>Phrase {i+1}</option>)}</select></label><div className="tool-row"><button onClick={()=>void listen()}>Replay phrase · AI narration</button><button onClick={()=>setReveal(!reveal)}>{reveal?"Hide phrase":"Reveal this phrase"}</button><button onClick={()=>{stop();setStatus("");}}>Stop phrase</button></div>{reveal&&<p>{sentences[selected]}</p>}<p role="status">{status}</p></section>;
}
