"use client";
import {useEffect,useRef,useState,type RefObject} from "react";
import {captureActive,CAPTURE_PLAYBACK_EVENT,holdAppPlayback} from "../lib/audio-capture";
export default function ReplayTools({text,audio,loadAudio}:{text:string;audio:RefObject<HTMLAudioElement|null>;loadAudio:(text:string)=>Promise<Blob>}){
 const sentences=text.split(/(?<=[.!?…])\s+|\n+/u).filter(Boolean),[selected,setSelected]=useState(0),[reveal,setReveal]=useState(false),[a,setA]=useState<number|null>(null),[b,setB]=useState<number|null>(null),[loop,setLoop]=useState(false),[status,setStatus]=useState("");
 const player=useRef<HTMLAudioElement|null>(null),url=useRef(""),generation=useRef(0);
 const stop=()=>{generation.current++;player.current?.pause();player.current=null;if(url.current)URL.revokeObjectURL(url.current);url.current="";};
 useEffect(()=>{const pause=()=>{stop();setStatus("");};window.addEventListener(CAPTURE_PLAYBACK_EVENT,pause);return()=>{stop();window.removeEventListener(CAPTURE_PLAYBACK_EVENT,pause);};},[]);
 useEffect(()=>{const tick=()=>{if(loop&&a!==null&&b!==null&&audio.current&&audio.current.currentTime>=b)audio.current.currentTime=a;};const id=window.setInterval(tick,100);return()=>clearInterval(id);},[loop,a,b,audio]);
 const listen=async()=>{if(captureActive())return;const release=holdAppPlayback();release();stop();const attempt=generation.current;setStatus("Preparing phrase…");try{const blob=await loadAudio(sentences[selected]);if(attempt!==generation.current||captureActive())return;url.current=URL.createObjectURL(blob);player.current=new Audio(url.current);player.current.onended=()=>setStatus("");await player.current.play();setStatus("Listening to this phrase");}catch{if(attempt===generation.current)setStatus("Could not play this phrase. Please retry.");}};
 return <section className="practice-tools" aria-label="Focused replay tools"><h3>I couldn’t hear this part</h3><p>Replay the original recording, or isolate a phrase with AI narration.</p><div className="tool-row"><button onClick={()=>{if(audio.current)audio.current.currentTime=Math.max(0,audio.current.currentTime-5);}}>Back 5 seconds</button><button onClick={()=>{setA(audio.current?.currentTime??0);setB(null);setLoop(false);}}>Mark A</button><button disabled={a===null} onClick={()=>{const time=audio.current?.currentTime??0;if(a!==null&&time>a+.5)setB(time);else setStatus("Play at least half a second beyond A before marking B.");}}>Mark B</button><button disabled={a===null||b===null} aria-pressed={loop} onClick={()=>{setLoop(!loop);if(!loop&&audio.current&&a!==null)audio.current.currentTime=a;}}>{loop?"Stop loop":"Loop A–B"}</button></div><p>{a!==null?`A: ${a.toFixed(1)}s`:"A not set"} · {b!==null?`B: ${b.toFixed(1)}s`:"B not set"}</p><label>Phrase <select value={selected} onChange={e=>{stop();setSelected(Number(e.target.value));setReveal(false);setStatus("");}}>{sentences.map((_,i)=><option key={i} value={i}>Phrase {i+1}</option>)}</select></label><div className="tool-row"><button onClick={()=>void listen()}>Replay phrase</button><button onClick={()=>setReveal(!reveal)}>{reveal?"Hide phrase":"Reveal this phrase"}</button><button onClick={()=>{stop();setStatus("");}}>Stop phrase</button></div>{reveal&&<p>{sentences[selected]}</p>}<p role="status">{status}</p></section>;
}
