"use client";
import {useEffect,useRef,useState} from "react";
import {swedishDailyMinutes,swedishDictations,swedishFoundations,swedishListeningLadders,swedishMissions,swedishNouns,swedishSentences,swedishSounds} from "../content/swedish-lab";
import {dailySwedishIndex,evaluateSwedishDictation,sentenceAnswerIsCorrect,type SwedishLabState} from "../lib/swedish-lab";

type Section="path"|"words"|"sounds"|"missions";
type SoundMode="pairs"|"ladder"|"dictation";

function today(){const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-")}
function addUnique(items:string[],item:string){return items.includes(item)?items:[...items,item]}

function useLabAudio(loadAudio:(text:string)=>Promise<Blob>){
 const ref=useRef<HTMLAudioElement|null>(null),url=useRef("");const [active,setActive]=useState(""),[busy,setBusy]=useState(""),[error,setError]=useState("");
 useEffect(()=>()=>{ref.current?.pause();if(url.current)URL.revokeObjectURL(url.current)},[]);
 const stop=()=>{ref.current?.pause();setActive("")};
 const play=async(text:string,rate=.88)=>{if(active===text&&ref.current&&!ref.current.paused){stop();return}ref.current?.pause();setBusy(text);setError("");try{const blob=await loadAudio(text);if(url.current)URL.revokeObjectURL(url.current);url.current=URL.createObjectURL(blob);const audio=new Audio(url.current);ref.current=audio;audio.playbackRate=rate;audio.onended=()=>setActive("");audio.onerror=()=>{setActive("");setError("The Swedish voice is temporarily unavailable.")};await audio.play();setActive(text)}catch{setError("The Swedish voice is temporarily unavailable.")}finally{setBusy("")}};
 return {play,stop,active,busy,error};
}

export default function SwedishLab({completedLessons,state,onChange,onLesson,loadAudio,syncState}:{completedLessons:string[];state:SwedishLabState;onChange:(state:SwedishLabState)=>void;onLesson:(id:string)=>void;loadAudio:(text:string)=>Promise<Blob>;syncState:"local"|"syncing"|"synced"}){
 const [section,setSection]=useState<Section>("path"),[soundMode,setSoundMode]=useState<SoundMode>("pairs");
 const audio=useLabAudio(loadAudio);const date=today(),daily=swedishDailyMinutes[dailySwedishIndex(date,swedishDailyMinutes.length)],minuteDone=state.dailyMinuteDates.includes(date);
 const completeActivity=(id:string)=>onChange({...state,completedActivityIds:addUnique(state.completedActivityIds,id)});
 const completeMinute=()=>onChange({...state,dailyMinuteDates:addUnique(state.dailyMinuteDates,date),completedActivityIds:addUnique(state.completedActivityIds,daily.id)});
 const lessonCount=swedishFoundations.flatMap(unit=>unit.lessonIds).filter(id=>completedLessons.includes(id)).length;
 const activityTotal=swedishSentences.length+swedishSounds.length+swedishListeningLadders.length+swedishDictations.length;
 const activityDone=state.completedActivityIds.filter(id=>/^(v2|question|negation|location|request|fika-plan|i-y|u-o|a-a|a-e|long-short|sj|tj|stress|ladder|dict)/.test(id)).length;
 const progress=Math.round((lessonCount+activityDone+state.masteredNounIds.length+state.completedMissionIds.length)/(12+activityTotal+swedishNouns.length+swedishMissions.length)*100);
 const go=(next:Section)=>{audio.stop();setSection(next);window.scrollTo({top:0,behavior:"smooth"})};
 return <section className="swedish-lab" data-phrase-source="swedish-lab" aria-labelledby="swedish-lab-title">
  <header className="swedish-lab-hero"><div><p className="eyebrow">Swedish · A1 beginner lab</p><h1 id="swedish-lab-title">Build a small Swedish life.</h1><p>Learn the words you need, hear what makes Swedish sound Swedish, then use it in a situation. Each activity is short enough to repeat.</p><div className="lab-sync"><span>{syncState==="synced"?"✓ Saved with your Swedish progress":syncState==="syncing"?"Saving progress…":"Progress will sync when the connection returns"}</span><span>{progress}% explored</span></div></div><div className="lab-hero-mark" aria-hidden="true"><span>å</span><small>en början</small></div></header>
  <nav className="lab-nav" aria-label="Swedish Lab sections">{([{id:"path",label:"Path",sub:"What to learn"},{id:"words",label:"Build",sub:"Sentences & nouns"},{id:"sounds",label:"Hear",sub:"Sounds & dictation"},{id:"missions",label:"Use",sub:"Real-life missions"}] as const).map(item=><button key={item.id} className={section===item.id?"active":""} aria-current={section===item.id?"page":undefined} onClick={()=>go(item.id)}><span>{item.label}</span><small>{item.sub}</small></button>)}</nav>
  {audio.error&&<p className="lab-error" role="alert">{audio.error}</p>}
  {section==="path"&&<PathSection completedLessons={completedLessons} daily={daily} minuteDone={minuteDone} onCompleteMinute={completeMinute} onLesson={onLesson} play={audio.play} busy={audio.busy}/>} 
  {section==="words"&&<WordsSection state={state} onChange={onChange} completeActivity={completeActivity}/>} 
  {section==="sounds"&&<SoundsSection state={state} mode={soundMode} setMode={setSoundMode} completeActivity={completeActivity} play={audio.play} active={audio.active} busy={audio.busy}/>} 
  {section==="missions"&&<MissionsSection state={state} onChange={onChange} play={audio.play} busy={audio.busy}/>} 
 </section>
}

function ListenButton({text,play,busy,label="Listen"}:{text:string;play:(text:string,rate?:number)=>void;busy:string;label?:string}){return <button className="lab-listen" disabled={busy===text} onClick={()=>play(text)} aria-label={`${label}: ${text}`}><span aria-hidden="true">▶</span>{busy===text?"Loading…":label}</button>}

function PathSection({completedLessons,daily,minuteDone,onCompleteMinute,onLesson,play,busy}:{completedLessons:string[];daily:typeof swedishDailyMinutes[number];minuteDone:boolean;onCompleteMinute:()=>void;onLesson:(id:string)=>void;play:(text:string,rate?:number)=>void;busy:string}){
 const [revealed,setRevealed]=useState(false);
 return <div className="lab-section">
  <div className="lab-section-heading"><div><p className="eyebrow">Start here</p><h2>A path made of things you can do.</h2></div><p>Lesson completion comes from the full four-step listening loop. The small practices below prepare you for it.</p></div>
  <article className={`minute-card ${minuteDone?"done":""}`}><div className="minute-number">01:00</div><div><p className="eyebrow">Today’s one-minute Swedish</p><h3>{daily.text}</h3><div className="minute-actions"><ListenButton text={daily.text} play={play} busy={busy}/><button className="lab-text-button" onClick={()=>setRevealed(value=>!value)}>{revealed?"Hide meaning":"Reveal meaning"}</button></div>{revealed&&<div className="minute-reveal"><p>{daily.meaning}</p><strong>Make it yours</strong><span>{daily.prompt}</span></div>}<button className="lab-primary" disabled={minuteDone||!revealed} onClick={onCompleteMinute}>{minuteDone?"✓ Complete today":"I practised it"}</button></div></article>
  <div className="foundation-path">{swedishFoundations.map((unit,index)=>{const done=unit.lessonIds.filter(id=>completedLessons.includes(id)).length,next=unit.lessonIds.find(id=>!completedLessons.includes(id))||unit.lessonIds[0];return <article key={unit.id} className={done===unit.lessonIds.length?"complete":""}><div className="foundation-line" aria-hidden="true"><span>{done===unit.lessonIds.length?"✓":unit.number}</span>{index<swedishFoundations.length-1&&<i/>}</div><div><div className="foundation-title"><p className="eyebrow">Foundation {unit.number}</p><em>{done}/{unit.lessonIds.length} lessons</em></div><h3>{unit.title}</h3><p><b>I can:</b> {unit.canDo}</p><blockquote>{unit.accent}</blockquote><button onClick={()=>onLesson(next)}>{done===unit.lessonIds.length?"Practise again":"Start next lesson"} <span>→</span></button></div></article>})}</div>
 </div>
}

function WordsSection({state,onChange,completeActivity}:{state:SwedishLabState;onChange:(state:SwedishLabState)=>void;completeActivity:(id:string)=>void}){
 const [sentenceIndex,setSentenceIndex]=useState(0),[chosen,setChosen]=useState<number[]>([]),[sentenceResult,setSentenceResult]=useState<""|"right"|"wrong">("");
 const [nounIndex,setNounIndex]=useState(0),[flipped,setFlipped]=useState(false);const sentence=swedishSentences[sentenceIndex],noun=swedishNouns[nounIndex];
 const bankOrder=bankOrderFor(sentence.tokens.length,sentenceIndex);
 const choose=(index:number)=>{setChosen(items=>[...items,index]);setSentenceResult("")};
 const check=()=>{const correct=sentenceAnswerIsCorrect(chosen.map(index=>sentence.tokens[index]),sentence.answers);setSentenceResult(correct?"right":"wrong");if(correct)completeActivity(sentence.id)};
 const nextSentence=()=>{setSentenceIndex(index=>(index+1)%swedishSentences.length);setChosen([]);setSentenceResult("")};
 const toggleMastery=()=>onChange({...state,masteredNounIds:state.masteredNounIds.includes(noun.id)?state.masteredNounIds.filter(id=>id!==noun.id):addUnique(state.masteredNounIds,noun.id)});
  return <div className="lab-section"><div className="lab-section-heading"><div><p className="eyebrow">Build</p><h2>See the sentence take shape.</h2></div><p>Swedish word order becomes easier when you move whole chunks—not when you memorize a grammar paragraph.</p></div>
  <div className="builder-grid"><article className="sentence-builder"><header><span>{sentenceIndex+1} / {swedishSentences.length}</span><small>{state.completedActivityIds.includes(sentence.id)?"✓ practised":"V2 word order"}</small></header><p className="builder-prompt">{sentence.prompt}</p><div className="sentence-target" aria-label="Your Swedish sentence">{chosen.length?chosen.map((index,position)=><button key={`${index}-${position}`} onClick={()=>{setChosen(items=>items.filter((_,i)=>i!==position));setSentenceResult("")}}>{sentence.tokens[index]}</button>):<span>Choose the Swedish words in order…</span>}</div><div className="word-bank">{bankOrder.map(index=><button key={`${sentence.tokens[index]}-${index}`} disabled={chosen.includes(index)} onClick={()=>choose(index)}>{sentence.tokens[index]}</button>)}</div>{sentenceResult&&<div className={`builder-result ${sentenceResult}`} role="status"><strong>{sentenceResult==="right"?"Bra! That works.":"Nearly—move the verb into its Swedish place."}</strong><p>{sentence.note}</p></div>}<footer><button className="lab-text-button" onClick={()=>{setChosen([]);setSentenceResult("")}}>Reset</button>{sentenceResult==="right"?<button className="lab-primary" onClick={nextSentence}>Next sentence →</button>:<button className="lab-primary" disabled={chosen.length!==sentence.tokens.length} onClick={check}>Check sentence</button>}</footer></article>
   <aside className="grammar-note"><span aria-hidden="true">2</span><p className="eyebrow">The useful rule</p><h3>The verb likes second place.</h3><p><b>Jag jobbar i dag.</b><br/>I work today.</p><p><b>I dag jobbar jag.</b><br/>Today I work.</p><small>The first position can change, but the verb usually stays second in a main statement.</small></aside></div>
  <div className="noun-workshop"><div className="lab-section-heading compact"><div><p className="eyebrow">En / ett collection</p><h2>Learn the noun with its shape.</h2></div><p>{state.masteredNounIds.length}/{swedishNouns.length} feel familiar</p></div><div className="noun-layout"><div className={`noun-card ${flipped?"flipped":""}`}><div><span>{noun.group}</span><small>Card {nounIndex+1} of {swedishNouns.length}</small></div><button onClick={()=>setFlipped(value=>!value)} aria-label={flipped?"Hide noun forms":"Reveal noun forms"}>{flipped?<><strong>{noun.article} {noun.noun}</strong><p>{noun.definite} · {noun.plural}</p><em>the {noun.meaning} · plural</em></>:<><strong>{noun.meaning}</strong><p>en or ett?</p><em>Tap to reveal</em></>}</button></div><div className="noun-controls"><button onClick={()=>{setNounIndex(index=>(index+swedishNouns.length-1)%swedishNouns.length);setFlipped(false)}}>← Previous</button><button className={state.masteredNounIds.includes(noun.id)?"known":""} disabled={!flipped} onClick={toggleMastery}>{state.masteredNounIds.includes(noun.id)?"✓ Feels familiar":"Mark familiar"}</button><button onClick={()=>{setNounIndex(index=>(index+1)%swedishNouns.length);setFlipped(false)}}>Next →</button></div></div></div>
 </div>
}

function bankOrderFor(length:number,seed:number){
 const order=Array.from({length},(_,index)=>index);if(length<2)return order;const pivot=(seed*2+1)%length;return [...order.slice(pivot),...order.slice(0,pivot)].reverse();
}

function SoundsSection({state,mode,setMode,completeActivity,play,active,busy}:{state:SwedishLabState;mode:SoundMode;setMode:(mode:SoundMode)=>void;completeActivity:(id:string)=>void;play:(text:string,rate?:number)=>void;active:string;busy:string}){
 return <div className="lab-section"><div className="lab-section-heading"><div><p className="eyebrow">Hear</p><h2>Train the contrast, not an accent score.</h2></div><p>These activities help you notice Swedish. They do not diagnose pronunciation from a microphone.</p></div><div className="sound-mode" role="tablist" aria-label="Listening activity">{([{id:"pairs",label:"Sound pairs"},{id:"ladder",label:"Transcript ladder"},{id:"dictation",label:"Dictation"}] as const).map(item=><button role="tab" aria-selected={mode===item.id} key={item.id} onClick={()=>setMode(item.id)}>{item.label}</button>)}</div>
  {mode==="pairs"&&<SoundPairs state={state} completeActivity={completeActivity} play={play} busy={busy}/>} 
  {mode==="ladder"&&<ListeningLadder state={state} completeActivity={completeActivity} play={play} busy={busy}/>} 
  {mode==="dictation"&&<Dictation state={state} completeActivity={completeActivity} play={play} active={active} busy={busy}/>} 
 </div>
}

function SoundPairs({state,completeActivity,play,busy}:{state:SwedishLabState;completeActivity:(id:string)=>void;play:(text:string,rate?:number)=>void;busy:string}){
 const [index,setIndex]=useState(0),[choice,setChoice]=useState("");const item=swedishSounds[index];
 return <article className="sound-practice"><header><div><span>Sound {index+1} of {swedishSounds.length}</span><strong>{item.focus}</strong></div><small>{state.completedActivityIds.includes(item.id)?"✓ noticed":"Listen, then choose"}</small></header><div className="sound-buttons"><ListenButton text={item.left} play={play} busy={busy} label={item.left}/><ListenButton text={item.right} play={play} busy={busy} label={item.right}/></div><h3>{item.prompt}</h3><div className="choice-row">{[item.left,item.right].map(word=><button key={word} className={choice===word?word===item.answer?"right":"wrong":""} onClick={()=>{setChoice(word);if(word===item.answer)completeActivity(item.id)}}>{word}</button>)}</div>{choice&&<div className="sound-tip" role="status"><strong>{choice===item.answer?"Yes—listen once more.":`Listen again for ${item.answer}.`}</strong><p>{item.tip}</p></div>}<button className="lab-primary" onClick={()=>{setIndex(value=>(value+1)%swedishSounds.length);setChoice("")}}>Next contrast →</button></article>
}

function ListeningLadder({state,completeActivity,play,busy}:{state:SwedishLabState;completeActivity:(id:string)=>void;play:(text:string,rate?:number)=>void;busy:string}){
 const [index,setIndex]=useState(0),[level,setLevel]=useState(0);const item=swedishListeningLadders[index];
 return <article className="ladder-practice"><header><span>Passage {index+1} of {swedishListeningLadders.length}</span><small>{state.completedActivityIds.includes(item.id)?"✓ heard":"Use only the help you need"}</small></header><h3>Listen before you read.</h3><ListenButton text={item.audio} play={play} busy={busy}/><ol><li className={level>=0?"open":""}><span>1</span><div><strong>Audio only</strong><p>Catch the situation and any words you know.</p></div></li><li className={level>=1?"open":""}><span>2</span><div><strong>Letter clues</strong>{level>=1?<p className="swedish-text">{item.hint}</p>:<button onClick={()=>setLevel(1)}>Show a small hint</button>}</div></li><li className={level>=2?"open":""}><span>3</span><div><strong>Full sentence</strong>{level>=2?<><p className="swedish-text">{item.audio}</p><em>{item.translation}</em></>:<button onClick={()=>{setLevel(2);completeActivity(item.id)}}>Reveal transcript</button>}</div></li></ol><button className="lab-primary" onClick={()=>{setIndex(value=>(value+1)%swedishListeningLadders.length);setLevel(0)}}>Next passage →</button></article>
}

function Dictation({state,completeActivity,play,busy}:{state:SwedishLabState;completeActivity:(id:string)=>void;play:(text:string,rate?:number)=>void;active:string;busy:string}){
 const [index,setIndex]=useState(0),[input,setInput]=useState(""),[result,setResult]=useState<""|"correct"|"marks"|"retry">(""),[answerVisible,setAnswerVisible]=useState(false);const item=swedishDictations[index];
 const check=()=>{const next=evaluateSwedishDictation(input,item.text);setResult(next);setAnswerVisible(false);if(next==="correct")completeActivity(item.id)};
 return <article className="dictation-practice"><header><span>Dictation {index+1} of {swedishDictations.length}</span><small>{state.completedActivityIds.includes(item.id)?"✓ written":"Listen as often as you need"}</small></header><h3>Type what you hear.</h3><ListenButton text={item.text} play={play} busy={busy}/><label htmlFor="swedish-dictation">Your Swedish</label><textarea id="swedish-dictation" value={input} onChange={event=>{setInput(event.target.value);setResult("");setAnswerVisible(false)}} placeholder="Skriv på svenska…"/><div className="special-letters" aria-label="Swedish letters">{["å","ä","ö","Å","Ä","Ö"].map(letter=><button key={letter} onClick={()=>setInput(value=>value+letter)}>{letter}</button>)}</div>{result&&<div className={`dictation-result ${result}`} role="status">{result==="correct"?<><strong>Precis! You heard and spelled it.</strong><p>{item.meaning}</p></>:result==="marks"?<><strong>Your listening is right; check the Swedish marks.</strong><p>Compare Å, Ä, and Ö: <b>{item.text}</b></p></>:<><strong>One more listen.</strong><p>{answerVisible?<><b>{item.text}</b><br/>{item.meaning}</>:"Use the rhythm and word boundaries before revealing the answer."}</p>{!answerVisible&&<button onClick={()=>setAnswerVisible(true)}>Show the sentence</button>}</>}</div>}<footer>{result==="correct"?<button className="lab-primary" onClick={()=>{setIndex(value=>(value+1)%swedishDictations.length);setInput("");setResult("");setAnswerVisible(false)}}>Next dictation →</button>:<button className="lab-primary" disabled={!input.trim()} onClick={check}>Check what I heard</button>}</footer></article>
}

function MissionsSection({state,onChange,play,busy}:{state:SwedishLabState;onChange:(state:SwedishLabState)=>void;play:(text:string,rate?:number)=>void;busy:string}){
 const [missionId,setMissionId]=useState(""),[stepIndex,setStepIndex]=useState(0),[choice,setChoice]=useState(""),[finished,setFinished]=useState(false);const mission=swedishMissions.find(item=>item.id===missionId);const step=mission?.steps[stepIndex];
 const open=(id:string)=>{setMissionId(id);setStepIndex(0);setChoice("");setFinished(false)};
 if(mission&&step)return <div className="lab-section"><button className="mission-back" onClick={()=>setMissionId("")}>← All missions</button><article className="mission-stage"><header><div><span aria-hidden="true">{mission.icon}</span><div><p className="eyebrow">{mission.setting}</p><h2>{mission.title}</h2></div></div><small>{stepIndex+1} / {mission.steps.length}</small></header>{finished?<div className="mission-finish"><span>✓</span><h3>Mission complete.</h3><p>You got what you needed without translating every word.</p><button className="lab-primary" onClick={()=>setMissionId("")}>Choose another mission</button></div>:<><div className="mission-speaker"><ListenButton text={step.line} play={play} busy={busy}/><blockquote>{step.line}</blockquote><button onClick={()=>setChoice(value=>value==="meaning"?"":"meaning")}>{choice==="meaning"?step.meaning:"Need the meaning?"}</button></div><p className="mission-prompt">What do you say?</p><div className="mission-choices">{[...step.choices].sort((a,b)=>a.localeCompare(b,"sv")).map(answer=><button key={answer} disabled={choice!==""&&choice!=="meaning"} onClick={()=>setChoice(answer)}>{answer}</button>)}</div>{choice&&choice!=="meaning"&&<div className={`mission-reply ${choice===step.choices[step.answer]?"right":"wrong"}`} role="status"><strong>{choice===step.choices[step.answer]?step.reply:"That answer belongs to a different situation."}</strong>{choice===step.choices[step.answer]?<button className="lab-primary" onClick={()=>{if(stepIndex===mission.steps.length-1){setFinished(true);onChange({...state,completedMissionIds:addUnique(state.completedMissionIds,mission.id)})}else{setStepIndex(value=>value+1);setChoice("")}}}>{stepIndex===mission.steps.length-1?"Finish mission":"Continue →"}</button>:<button className="lab-text-button" onClick={()=>setChoice("")}>Try again</button>}</div>}</>}</article></div>;
 return <div className="lab-section"><div className="lab-section-heading"><div><p className="eyebrow">Use</p><h2>Get through the moment.</h2></div><p>These branching mini-scenes test the useful response, not a perfect translation.</p></div><div className="mission-grid">{swedishMissions.map(item=><article key={item.id} className={state.completedMissionIds.includes(item.id)?"complete":""}><span aria-hidden="true">{item.icon}</span><p className="eyebrow">{item.setting}</p><h3>{item.title}</h3><p>{item.goal}</p><footer><small>{state.completedMissionIds.includes(item.id)?"✓ completed":"3 choices"}</small><button onClick={()=>open(item.id)}>{state.completedMissionIds.includes(item.id)?"Try again":"Start mission"} →</button></footer></article>)}</div></div>
}
